use std::fmt;

use chrono::naive::NaiveDate;
use graphql_client::GraphQLQuery;
use thoth_api::model::contribution::ContributionType;
use thoth_api::model::language::LanguageRelation;
use thoth_api::model::locale::LocaleCode;
use thoth_api::model::publication::PublicationType;
use thoth_api::model::Doi;
use thoth_api::model::Isbn;
use thoth_api::model::Orcid;
use thoth_api::model::Ror;
use thoth_api::model::Timestamp;
use uuid::Uuid;

// Juniper v0.16 onwards converts Rust `NaiveDate` to GraphQL scalar `Date`,
// so we need to convert it back explicitly here (was previously automatic)
pub type Date = NaiveDate;

#[derive(GraphQLQuery)]
#[graphql(
    schema_path = "assets/schema.graphql",
    query_path = "assets/queries.graphql",
    response_derives = "Debug,Clone,Deserialize,Serialize,PartialEq",
    variables_derives = "Debug,PartialEq"
)]
pub struct WorkQuery;

impl fmt::Display for work_query::LanguageCode {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{self:?}")
    }
}

impl fmt::Display for work_query::CurrencyCode {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{self:?}")
    }
}

impl fmt::Display for work_query::SubjectType {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{self:?}")
    }
}

impl fmt::Display for work_query::PublicationType {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{self:?}")
    }
}

impl fmt::Display for work_query::LocationPlatform {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{self:?}")
    }
}

impl fmt::Display for work_query::LocaleCode {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{self:?}")
    }
}

#[derive(GraphQLQuery)]
#[graphql(
    schema_path = "assets/schema.graphql",
    query_path = "assets/queries.graphql",
    response_derives = "Debug,Clone,Deserialize,Serialize,PartialEq",
    variables_derives = "Debug,PartialEq"
)]
pub struct WorksQuery;

#[derive(GraphQLQuery)]
#[graphql(
    schema_path = "assets/schema.graphql",
    query_path = "assets/queries.graphql",
    response_derives = "Debug,Clone,Deserialize,Serialize,PartialEq",
    variables_derives = "Debug,PartialEq"
)]
pub struct WorkCountQuery;

#[derive(GraphQLQuery)]
#[graphql(
    schema_path = "assets/schema.graphql",
    query_path = "assets/queries.graphql",
    response_derives = "Debug,Clone,Deserialize,Serialize,PartialEq",
    variables_derives = "Debug,PartialEq"
)]
pub struct WorkLastUpdatedQuery;

#[derive(GraphQLQuery)]
#[graphql(
    schema_path = "assets/schema.graphql",
    query_path = "assets/queries.graphql",
    response_derives = "Debug,Clone,Deserialize,Serialize,PartialEq",
    variables_derives = "Debug,PartialEq"
)]
pub struct WorksLastUpdatedQuery;

// Needed to set work_query::Work as the canonical struct for the shared fragment in the two queries
// until https://github.com/graphql-rust/graphql-client/issues/312 gets fixed
impl From<works_query::Work> for work_query::Work {
    fn from(w: works_query::Work) -> Self {
        let se = serde_json::to_string(&w).unwrap();
        serde_json::from_str(&se).unwrap()
    }
}

// As above: enables shared processing of parent Works and child RelatedWorks in doideposit format
impl From<work_query::Work> for work_query::WorkRelationsRelatedWork {
    fn from(w: work_query::Work) -> Self {
        let se = serde_json::to_string(&w).unwrap();
        serde_json::from_str(&se).unwrap()
    }
}

// Allow conversion to the original ContributionType to benefit from trait implementations
impl From<work_query::ContributionType> for ContributionType {
    fn from(value: work_query::ContributionType) -> Self {
        match value {
            work_query::ContributionType::AUTHOR => ContributionType::Author,
            work_query::ContributionType::EDITOR => ContributionType::Editor,
            work_query::ContributionType::TRANSLATOR => ContributionType::Translator,
            work_query::ContributionType::PHOTOGRAPHER => ContributionType::Photographer,
            work_query::ContributionType::ILLUSTRATOR => ContributionType::Illustrator,
            work_query::ContributionType::MUSIC_EDITOR => ContributionType::MusicEditor,
            work_query::ContributionType::FOREWORD_BY => ContributionType::ForewordBy,
            work_query::ContributionType::INTRODUCTION_BY => ContributionType::IntroductionBy,
            work_query::ContributionType::AFTERWORD_BY => ContributionType::AfterwordBy,
            work_query::ContributionType::PREFACE_BY => ContributionType::PrefaceBy,
            work_query::ContributionType::SOFTWARE_BY => ContributionType::SoftwareBy,
            work_query::ContributionType::RESEARCH_BY => ContributionType::ResearchBy,
            work_query::ContributionType::CONTRIBUTIONS_BY => ContributionType::ContributionsBy,
            work_query::ContributionType::INDEXER => ContributionType::Indexer,
            _ => unreachable!(),
        }
    }
}

impl From<work_query::PublicationType> for PublicationType {
    fn from(value: crate::PublicationType) -> Self {
        match value {
            work_query::PublicationType::PAPERBACK => PublicationType::Paperback,
            work_query::PublicationType::HARDBACK => PublicationType::Hardback,
            work_query::PublicationType::PDF => PublicationType::Pdf,
            work_query::PublicationType::HTML => PublicationType::Html,
            work_query::PublicationType::XML => PublicationType::Xml,
            work_query::PublicationType::EPUB => PublicationType::Epub,
            work_query::PublicationType::MOBI => PublicationType::Mobi,
            work_query::PublicationType::AZW3 => PublicationType::Azw3,
            work_query::PublicationType::DOCX => PublicationType::Docx,
            work_query::PublicationType::FICTION_BOOK => PublicationType::FictionBook,
            work_query::PublicationType::MP3 => PublicationType::Mp3,
            work_query::PublicationType::WAV => PublicationType::Wav,
            work_query::PublicationType::Other(_) => unreachable!(),
        }
    }
}

impl From<work_query::LanguageRelation> for LanguageRelation {
    fn from(value: crate::LanguageRelation) -> Self {
        match value {
            work_query::LanguageRelation::ORIGINAL => LanguageRelation::Original,
            work_query::LanguageRelation::TRANSLATED_FROM => LanguageRelation::TranslatedFrom,
            work_query::LanguageRelation::TRANSLATED_INTO => LanguageRelation::TranslatedInto,
            work_query::LanguageRelation::Other(_) => unreachable!(),
        }
    }
}

// Convert generated GraphQL LocaleCode into API LocaleCode
impl From<work_query::LocaleCode> for LocaleCode {
    fn from(value: work_query::LocaleCode) -> Self {
        match value {
            work_query::LocaleCode::EN => LocaleCode::En,
            work_query::LocaleCode::AF => LocaleCode::Af,
            work_query::LocaleCode::AF_NA => LocaleCode::AfNa,
            work_query::LocaleCode::AF_ZA => LocaleCode::AfZa,
            work_query::LocaleCode::AGQ => LocaleCode::Agq,
            work_query::LocaleCode::AGQ_CM => LocaleCode::AgqCm,
            work_query::LocaleCode::AK => LocaleCode::Ak,
            work_query::LocaleCode::AK_GH => LocaleCode::AkGh,
            work_query::LocaleCode::SQ => LocaleCode::Sq,
            work_query::LocaleCode::SQ_AL => LocaleCode::SqAl,
            work_query::LocaleCode::AM => LocaleCode::Am,
            work_query::LocaleCode::AM_ET => LocaleCode::AmEt,
            work_query::LocaleCode::AIG => LocaleCode::Aig,
            work_query::LocaleCode::AR => LocaleCode::Ar,
            work_query::LocaleCode::AR_DZ => LocaleCode::ArDz,
            work_query::LocaleCode::AR_BH => LocaleCode::ArBh,
            work_query::LocaleCode::AR_EG => LocaleCode::ArEg,
            work_query::LocaleCode::AR_IQ => LocaleCode::ArIq,
            work_query::LocaleCode::AR_JO => LocaleCode::ArJo,
            work_query::LocaleCode::AR_KW => LocaleCode::ArKw,
            work_query::LocaleCode::AR_LB => LocaleCode::ArLb,
            work_query::LocaleCode::AR_LY => LocaleCode::ArLy,
            work_query::LocaleCode::AR_MA => LocaleCode::ArMa,
            work_query::LocaleCode::AR_OM => LocaleCode::ArOm,
            work_query::LocaleCode::AR_QA => LocaleCode::ArQa,
            work_query::LocaleCode::AR_SA => LocaleCode::ArSa,
            work_query::LocaleCode::AR_SD => LocaleCode::ArSd,
            work_query::LocaleCode::AR_SY => LocaleCode::ArSy,
            work_query::LocaleCode::AR_TN => LocaleCode::ArTn,
            work_query::LocaleCode::AR_AE => LocaleCode::ArAe,
            work_query::LocaleCode::AR001 => LocaleCode::Ar001,
            work_query::LocaleCode::AR_YE => LocaleCode::ArYe,
            work_query::LocaleCode::HY => LocaleCode::Hy,
            work_query::LocaleCode::HY_AM => LocaleCode::HyAm,
            work_query::LocaleCode::AS => LocaleCode::As,
            work_query::LocaleCode::AS_IN => LocaleCode::AsIn,
            work_query::LocaleCode::AST => LocaleCode::Ast,
            work_query::LocaleCode::AST_ES => LocaleCode::AstEs,
            work_query::LocaleCode::ASA => LocaleCode::Asa,
            work_query::LocaleCode::ASA_TZ => LocaleCode::AsaTz,
            work_query::LocaleCode::AZ => LocaleCode::Az,
            work_query::LocaleCode::AZ_CYRL => LocaleCode::AzCyrl,
            work_query::LocaleCode::AZ_CYRL_AZ => LocaleCode::AzCyrlAz,
            work_query::LocaleCode::AZ_LATN => LocaleCode::AzLatn,
            work_query::LocaleCode::AZ_LATN_AZ => LocaleCode::AzLatnAz,
            work_query::LocaleCode::KSF => LocaleCode::Ksf,
            work_query::LocaleCode::KSF_CM => LocaleCode::KsfCm,
            work_query::LocaleCode::BAH => LocaleCode::Bah,
            work_query::LocaleCode::BM => LocaleCode::Bm,
            work_query::LocaleCode::BM_ML => LocaleCode::BmMl,
            work_query::LocaleCode::BAS => LocaleCode::Bas,
            work_query::LocaleCode::BAS_CM => LocaleCode::BasCm,
            work_query::LocaleCode::EU => LocaleCode::Eu,
            work_query::LocaleCode::EU_ES => LocaleCode::EuEs,
            work_query::LocaleCode::BE => LocaleCode::Be,
            work_query::LocaleCode::BE_BY => LocaleCode::BeBy,
            work_query::LocaleCode::BEM => LocaleCode::Bem,
            work_query::LocaleCode::BEM_ZM => LocaleCode::BemZm,
            work_query::LocaleCode::BEZ => LocaleCode::Bez,
            work_query::LocaleCode::BEZ_TZ => LocaleCode::BezTz,
            work_query::LocaleCode::BN => LocaleCode::Bn,
            work_query::LocaleCode::BN_BD => LocaleCode::BnBd,
            work_query::LocaleCode::BN_IN => LocaleCode::BnIn,
            work_query::LocaleCode::BRX => LocaleCode::Brx,
            work_query::LocaleCode::BRX_IN => LocaleCode::BrxIn,
            work_query::LocaleCode::BS => LocaleCode::Bs,
            work_query::LocaleCode::BS_BA => LocaleCode::BsBa,
            work_query::LocaleCode::BR => LocaleCode::Br,
            work_query::LocaleCode::BR_FR => LocaleCode::BrFr,
            work_query::LocaleCode::BG => LocaleCode::Bg,
            work_query::LocaleCode::BG_BG => LocaleCode::BgBg,
            work_query::LocaleCode::MY => LocaleCode::My,
            work_query::LocaleCode::MY_MM => LocaleCode::MyMm,
            work_query::LocaleCode::CA => LocaleCode::Ca,
            work_query::LocaleCode::CA_ES => LocaleCode::CaEs,
            work_query::LocaleCode::CKB => LocaleCode::Ckb,
            work_query::LocaleCode::KMR => LocaleCode::Kmr,
            work_query::LocaleCode::SDH => LocaleCode::Sdh,
            work_query::LocaleCode::TZM => LocaleCode::Tzm,
            work_query::LocaleCode::TZM_LATN => LocaleCode::TzmLatn,
            work_query::LocaleCode::TZM_LATN_MA => LocaleCode::TzmLatnMa,
            work_query::LocaleCode::CHR => LocaleCode::Chr,
            work_query::LocaleCode::CHR_US => LocaleCode::ChrUs,
            work_query::LocaleCode::CGG => LocaleCode::Cgg,
            work_query::LocaleCode::CGG_UG => LocaleCode::CggUg,
            work_query::LocaleCode::ZH => LocaleCode::Zh,
            work_query::LocaleCode::ZH_HANS => LocaleCode::ZhHans,
            work_query::LocaleCode::ZH_CN => LocaleCode::ZhCn,
            work_query::LocaleCode::ZH_HANS_CN => LocaleCode::ZhHansCn,
            work_query::LocaleCode::ZH_HANS_HK => LocaleCode::ZhHansHk,
            work_query::LocaleCode::ZH_HANS_MO => LocaleCode::ZhHansMo,
            work_query::LocaleCode::ZH_HANS_SG => LocaleCode::ZhHansSg,
            work_query::LocaleCode::ZH_HANT => LocaleCode::ZhHant,
            work_query::LocaleCode::ZH_HANT_HK => LocaleCode::ZhHantHk,
            work_query::LocaleCode::ZH_HANT_MO => LocaleCode::ZhHantMo,
            work_query::LocaleCode::ZH_HANT_TW => LocaleCode::ZhHantTw,
            work_query::LocaleCode::SWC => LocaleCode::Swc,
            work_query::LocaleCode::SWC_CD => LocaleCode::SwcCd,
            work_query::LocaleCode::KW => LocaleCode::Kw,
            work_query::LocaleCode::KW_GB => LocaleCode::KwGb,
            work_query::LocaleCode::HR => LocaleCode::Hr,
            work_query::LocaleCode::HR_HR => LocaleCode::HrHr,
            work_query::LocaleCode::CS => LocaleCode::Cs,
            work_query::LocaleCode::CS_CZ => LocaleCode::CsCz,
            work_query::LocaleCode::DA => LocaleCode::Da,
            work_query::LocaleCode::DA_DK => LocaleCode::DaDk,
            work_query::LocaleCode::DUA => LocaleCode::Dua,
            work_query::LocaleCode::DUA_CM => LocaleCode::DuaCm,
            work_query::LocaleCode::DV => LocaleCode::Dv,
            work_query::LocaleCode::NL => LocaleCode::Nl,
            work_query::LocaleCode::NL_AW => LocaleCode::NlAw,
            work_query::LocaleCode::NL_BE => LocaleCode::NlBe,
            work_query::LocaleCode::NL_CW => LocaleCode::NlCw,
            work_query::LocaleCode::NL_NL => LocaleCode::NlNl,
            work_query::LocaleCode::NL_SX => LocaleCode::NlSx,
            work_query::LocaleCode::EBU => LocaleCode::Ebu,
            work_query::LocaleCode::EBU_KE => LocaleCode::EbuKe,
            work_query::LocaleCode::EN_AI => LocaleCode::EnAi,
            work_query::LocaleCode::EN_AS => LocaleCode::EnAs,
            work_query::LocaleCode::EN_AU => LocaleCode::EnAu,
            work_query::LocaleCode::EN_AT => LocaleCode::EnAt,
            work_query::LocaleCode::EN_BB => LocaleCode::EnBb,
            work_query::LocaleCode::EN_BE => LocaleCode::EnBe,
            work_query::LocaleCode::EN_BZ => LocaleCode::EnBz,
            work_query::LocaleCode::EN_BM => LocaleCode::EnBm,
            work_query::LocaleCode::EN_BW => LocaleCode::EnBw,
            work_query::LocaleCode::EN_IO => LocaleCode::EnIo,
            work_query::LocaleCode::EN_BI => LocaleCode::EnBi,
            work_query::LocaleCode::EN_CM => LocaleCode::EnCm,
            work_query::LocaleCode::EN_CA => LocaleCode::EnCa,
            work_query::LocaleCode::EN_KY => LocaleCode::EnKy,
            work_query::LocaleCode::EN_CX => LocaleCode::EnCx,
            work_query::LocaleCode::EN_CC => LocaleCode::EnCc,
            work_query::LocaleCode::EN_CK => LocaleCode::EnCk,
            work_query::LocaleCode::EN_CY => LocaleCode::EnCy,
            work_query::LocaleCode::EN_DK => LocaleCode::EnDk,
            work_query::LocaleCode::EN_DG => LocaleCode::EnDg,
            work_query::LocaleCode::EN_DM => LocaleCode::EnDm,
            work_query::LocaleCode::EN_EG => LocaleCode::EnEg,
            work_query::LocaleCode::EN_ER => LocaleCode::EnEr,
            work_query::LocaleCode::EN_EU => LocaleCode::EnEu,
            work_query::LocaleCode::EN_FK => LocaleCode::EnFk,
            work_query::LocaleCode::EN_FJ => LocaleCode::EnFj,
            work_query::LocaleCode::EN_FI => LocaleCode::EnFi,
            work_query::LocaleCode::EN_GM => LocaleCode::EnGm,
            work_query::LocaleCode::EN_DE => LocaleCode::EnDe,
            work_query::LocaleCode::EN_GH => LocaleCode::EnGh,
            work_query::LocaleCode::EN_GI => LocaleCode::EnGi,
            work_query::LocaleCode::EN_GD => LocaleCode::EnGd,
            work_query::LocaleCode::EN_GU => LocaleCode::EnGu,
            work_query::LocaleCode::EN_GG => LocaleCode::EnGg,
            work_query::LocaleCode::EN_GY => LocaleCode::EnGy,
            work_query::LocaleCode::EN_HK => LocaleCode::EnHk,
            work_query::LocaleCode::EN_IN => LocaleCode::EnIn,
            work_query::LocaleCode::EN_IE => LocaleCode::EnIe,
            work_query::LocaleCode::EN_IM => LocaleCode::EnIm,
            work_query::LocaleCode::EN_IL => LocaleCode::EnIl,
            work_query::LocaleCode::EN_JM => LocaleCode::EnJm,
            work_query::LocaleCode::EN_JE => LocaleCode::EnJe,
            work_query::LocaleCode::EN_KE => LocaleCode::EnKe,
            work_query::LocaleCode::EN_KI => LocaleCode::EnKi,
            work_query::LocaleCode::EN_KW => LocaleCode::EnKw,
            work_query::LocaleCode::EN_LS => LocaleCode::EnLs,
            work_query::LocaleCode::EN_MO => LocaleCode::EnMo,
            work_query::LocaleCode::EN_MG => LocaleCode::EnMg,
            work_query::LocaleCode::EN_MW => LocaleCode::EnMw,
            work_query::LocaleCode::EN_MY => LocaleCode::EnMy,
            work_query::LocaleCode::EN_MT => LocaleCode::EnMt,
            work_query::LocaleCode::EN_MH => LocaleCode::EnMh,
            work_query::LocaleCode::EN_MU => LocaleCode::EnMu,
            work_query::LocaleCode::EN_FM => LocaleCode::EnFm,
            work_query::LocaleCode::EN_MS => LocaleCode::EnMs,
            work_query::LocaleCode::EN_NA => LocaleCode::EnNa,
            work_query::LocaleCode::EN_NR => LocaleCode::EnNr,
            work_query::LocaleCode::EN_NL => LocaleCode::EnNl,
            work_query::LocaleCode::EN_NZ => LocaleCode::EnNz,
            work_query::LocaleCode::EN_NG => LocaleCode::EnNg,
            work_query::LocaleCode::EN_NU => LocaleCode::EnNu,
            work_query::LocaleCode::EN_NF => LocaleCode::EnNf,
            work_query::LocaleCode::EN_MP => LocaleCode::EnMp,
            work_query::LocaleCode::EN_NO => LocaleCode::EnNo,
            work_query::LocaleCode::EN_PA => LocaleCode::EnPa,
            work_query::LocaleCode::EN_PK => LocaleCode::EnPk,
            work_query::LocaleCode::EN_PW => LocaleCode::EnPw,
            work_query::LocaleCode::EN_PG => LocaleCode::EnPg,
            work_query::LocaleCode::EN_PH => LocaleCode::EnPh,
            work_query::LocaleCode::EN_PN => LocaleCode::EnPn,
            work_query::LocaleCode::EN_PR => LocaleCode::EnPr,
            work_query::LocaleCode::EN_RW => LocaleCode::EnRw,
            work_query::LocaleCode::EN_WS => LocaleCode::EnWs,
            work_query::LocaleCode::EN_SA => LocaleCode::EnSa,
            work_query::LocaleCode::EN_SC => LocaleCode::EnSc,
            work_query::LocaleCode::EN_SL => LocaleCode::EnSl,
            work_query::LocaleCode::EN_SG => LocaleCode::EnSg,
            work_query::LocaleCode::EN_SX => LocaleCode::EnSx,
            work_query::LocaleCode::EN_SI => LocaleCode::EnSi,
            work_query::LocaleCode::EN_SB => LocaleCode::EnSb,
            work_query::LocaleCode::EN_SS => LocaleCode::EnSs,
            work_query::LocaleCode::EN_SH => LocaleCode::EnSh,
            work_query::LocaleCode::EN_KN => LocaleCode::EnKn,
            work_query::LocaleCode::EN_LC => LocaleCode::EnLc,
            work_query::LocaleCode::SVC => LocaleCode::Svc,
            work_query::LocaleCode::VIC => LocaleCode::Vic,
            work_query::LocaleCode::EN_SD => LocaleCode::EnSd,
            work_query::LocaleCode::EN_SZ => LocaleCode::EnSz,
            work_query::LocaleCode::EN_SE => LocaleCode::EnSe,
            work_query::LocaleCode::EN_CH => LocaleCode::EnCh,
            work_query::LocaleCode::EN_TZ => LocaleCode::EnTz,
            work_query::LocaleCode::EN_TK => LocaleCode::EnTk,
            work_query::LocaleCode::EN_TO => LocaleCode::EnTo,
            work_query::LocaleCode::EN_TT => LocaleCode::EnTt,
            work_query::LocaleCode::EN_TV => LocaleCode::EnTv,
            work_query::LocaleCode::EN_ZA => LocaleCode::EnZa,
            work_query::LocaleCode::EN_AE => LocaleCode::EnAe,
            work_query::LocaleCode::EN_UM => LocaleCode::EnUm,
            work_query::LocaleCode::EN_VI => LocaleCode::EnVi,
            work_query::LocaleCode::EN_US_POSIX => LocaleCode::EnUsPosix,
            work_query::LocaleCode::EN_UG => LocaleCode::EnUg,
            work_query::LocaleCode::EN_GB => LocaleCode::EnGb,
            work_query::LocaleCode::EN_US => LocaleCode::EnUs,
            work_query::LocaleCode::EN_VU => LocaleCode::EnVu,
            work_query::LocaleCode::EN_ZM => LocaleCode::EnZm,
            work_query::LocaleCode::EN_ZW => LocaleCode::EnZw,
            work_query::LocaleCode::EO => LocaleCode::Eo,
            work_query::LocaleCode::ET => LocaleCode::Et,
            work_query::LocaleCode::ET_EE => LocaleCode::EtEe,
            work_query::LocaleCode::EE => LocaleCode::Ee,
            work_query::LocaleCode::EE_GH => LocaleCode::EeGh,
            work_query::LocaleCode::EE_TG => LocaleCode::EeTg,
            work_query::LocaleCode::EWO => LocaleCode::Ewo,
            work_query::LocaleCode::EWO_CM => LocaleCode::EwoCm,
            work_query::LocaleCode::FO => LocaleCode::Fo,
            work_query::LocaleCode::FO_FO => LocaleCode::FoFo,
            work_query::LocaleCode::FIL => LocaleCode::Fil,
            work_query::LocaleCode::FIL_PH => LocaleCode::FilPh,
            work_query::LocaleCode::FI => LocaleCode::Fi,
            work_query::LocaleCode::FI_FI => LocaleCode::FiFi,
            work_query::LocaleCode::FR => LocaleCode::Fr,
            work_query::LocaleCode::FR_BE => LocaleCode::FrBe,
            work_query::LocaleCode::FR_BJ => LocaleCode::FrBj,
            work_query::LocaleCode::FR_BF => LocaleCode::FrBf,
            work_query::LocaleCode::FR_BI => LocaleCode::FrBi,
            work_query::LocaleCode::FR_CM => LocaleCode::FrCm,
            work_query::LocaleCode::FR_CA => LocaleCode::FrCa,
            work_query::LocaleCode::FR_CF => LocaleCode::FrCf,
            work_query::LocaleCode::FR_TD => LocaleCode::FrTd,
            work_query::LocaleCode::FR_KM => LocaleCode::FrKm,
            work_query::LocaleCode::FR_CG => LocaleCode::FrCg,
            work_query::LocaleCode::FR_CD => LocaleCode::FrCd,
            work_query::LocaleCode::FR_CI => LocaleCode::FrCi,
            work_query::LocaleCode::FR_DJ => LocaleCode::FrDj,
            work_query::LocaleCode::FR_GQ => LocaleCode::FrGq,
            work_query::LocaleCode::FR_FR => LocaleCode::FrFr,
            work_query::LocaleCode::FR_GF => LocaleCode::FrGf,
            work_query::LocaleCode::FR_GA => LocaleCode::FrGa,
            work_query::LocaleCode::FR_GP => LocaleCode::FrGp,
            work_query::LocaleCode::FR_GN => LocaleCode::FrGn,
            work_query::LocaleCode::FR_LU => LocaleCode::FrLu,
            work_query::LocaleCode::FR_MG => LocaleCode::FrMg,
            work_query::LocaleCode::FR_ML => LocaleCode::FrMl,
            work_query::LocaleCode::FR_MQ => LocaleCode::FrMq,
            work_query::LocaleCode::FR_YT => LocaleCode::FrYt,
            work_query::LocaleCode::FR_MC => LocaleCode::FrMc,
            work_query::LocaleCode::FR_NE => LocaleCode::FrNe,
            work_query::LocaleCode::FR_RW => LocaleCode::FrRw,
            work_query::LocaleCode::FR_RE => LocaleCode::FrRe,
            work_query::LocaleCode::FR_BL => LocaleCode::FrBl,
            work_query::LocaleCode::FR_MF => LocaleCode::FrMf,
            work_query::LocaleCode::FR_MU => LocaleCode::FrMu,
            work_query::LocaleCode::FR_SN => LocaleCode::FrSn,
            work_query::LocaleCode::FR_CH => LocaleCode::FrCh,
            work_query::LocaleCode::FR_TG => LocaleCode::FrTg,
            work_query::LocaleCode::FF => LocaleCode::Ff,
            work_query::LocaleCode::FF_SN => LocaleCode::FfSn,
            work_query::LocaleCode::GL => LocaleCode::Gl,
            work_query::LocaleCode::GL_ES => LocaleCode::GlEs,
            work_query::LocaleCode::LAO => LocaleCode::Lao,
            work_query::LocaleCode::LG => LocaleCode::Lg,
            work_query::LocaleCode::LG_UG => LocaleCode::LgUg,
            work_query::LocaleCode::KA => LocaleCode::Ka,
            work_query::LocaleCode::KA_GE => LocaleCode::KaGe,
            work_query::LocaleCode::DE => LocaleCode::De,
            work_query::LocaleCode::DE_AT => LocaleCode::DeAt,
            work_query::LocaleCode::DE_BE => LocaleCode::DeBe,
            work_query::LocaleCode::DE_DE => LocaleCode::DeDe,
            work_query::LocaleCode::DE_LI => LocaleCode::DeLi,
            work_query::LocaleCode::DE_LU => LocaleCode::DeLu,
            work_query::LocaleCode::DE_CH => LocaleCode::DeCh,
            work_query::LocaleCode::EL => LocaleCode::El,
            work_query::LocaleCode::EL_CY => LocaleCode::ElCy,
            work_query::LocaleCode::EL_GR => LocaleCode::ElGr,
            work_query::LocaleCode::GU => LocaleCode::Gu,
            work_query::LocaleCode::GU_IN => LocaleCode::GuIn,
            work_query::LocaleCode::GUZ => LocaleCode::Guz,
            work_query::LocaleCode::GUZ_KE => LocaleCode::GuzKe,
            work_query::LocaleCode::HA => LocaleCode::Ha,
            work_query::LocaleCode::HA_LATN => LocaleCode::HaLatn,
            work_query::LocaleCode::HA_LATN_GH => LocaleCode::HaLatnGh,
            work_query::LocaleCode::HA_LATN_NE => LocaleCode::HaLatnNe,
            work_query::LocaleCode::HA_LATN_NG => LocaleCode::HaLatnNg,
            work_query::LocaleCode::HAW => LocaleCode::Haw,
            work_query::LocaleCode::HAW_US => LocaleCode::HawUs,
            work_query::LocaleCode::HE => LocaleCode::He,
            work_query::LocaleCode::HE_IL => LocaleCode::HeIl,
            work_query::LocaleCode::HI => LocaleCode::Hi,
            work_query::LocaleCode::HI_IN => LocaleCode::HiIn,
            work_query::LocaleCode::HU => LocaleCode::Hu,
            work_query::LocaleCode::HU_HU => LocaleCode::HuHu,
            work_query::LocaleCode::IS => LocaleCode::Is,
            work_query::LocaleCode::IS_IS => LocaleCode::IsIs,
            work_query::LocaleCode::IG => LocaleCode::Ig,
            work_query::LocaleCode::IG_NG => LocaleCode::IgNg,
            work_query::LocaleCode::SMN => LocaleCode::Smn,
            work_query::LocaleCode::SMN_FI => LocaleCode::SmnFi,
            work_query::LocaleCode::ID => LocaleCode::Id,
            work_query::LocaleCode::ID_ID => LocaleCode::IdId,
            work_query::LocaleCode::GA => LocaleCode::Ga,
            work_query::LocaleCode::GA_IE => LocaleCode::GaIe,
            work_query::LocaleCode::IT => LocaleCode::It,
            work_query::LocaleCode::IT_IT => LocaleCode::ItIt,
            work_query::LocaleCode::IT_CH => LocaleCode::ItCh,
            work_query::LocaleCode::JA => LocaleCode::Ja,
            work_query::LocaleCode::JA_JP => LocaleCode::JaJp,
            work_query::LocaleCode::DYO => LocaleCode::Dyo,
            work_query::LocaleCode::DYO_SN => LocaleCode::DyoSn,
            work_query::LocaleCode::KEA => LocaleCode::Kea,
            work_query::LocaleCode::KEA_CV => LocaleCode::KeaCv,
            work_query::LocaleCode::KAB => LocaleCode::Kab,
            work_query::LocaleCode::KAB_DZ => LocaleCode::KabDz,
            work_query::LocaleCode::KL => LocaleCode::Kl,
            work_query::LocaleCode::KL_GL => LocaleCode::KlGl,
            work_query::LocaleCode::KLN => LocaleCode::Kln,
            work_query::LocaleCode::KLN_KE => LocaleCode::KlnKe,
            work_query::LocaleCode::KAM => LocaleCode::Kam,
            work_query::LocaleCode::KAM_KE => LocaleCode::KamKe,
            work_query::LocaleCode::KN => LocaleCode::Kn,
            work_query::LocaleCode::KN_IN => LocaleCode::KnIn,
            work_query::LocaleCode::KAA => LocaleCode::Kaa,
            work_query::LocaleCode::KK => LocaleCode::Kk,
            work_query::LocaleCode::KK_CYRL => LocaleCode::KkCyrl,
            work_query::LocaleCode::KK_CYRL_KZ => LocaleCode::KkCyrlKz,
            work_query::LocaleCode::KM => LocaleCode::Km,
            work_query::LocaleCode::KM_KH => LocaleCode::KmKh,
            work_query::LocaleCode::KI => LocaleCode::Ki,
            work_query::LocaleCode::KI_KE => LocaleCode::KiKe,
            work_query::LocaleCode::RW => LocaleCode::Rw,
            work_query::LocaleCode::RW_RW => LocaleCode::RwRw,
            work_query::LocaleCode::KOK => LocaleCode::Kok,
            work_query::LocaleCode::KOK_IN => LocaleCode::KokIn,
            work_query::LocaleCode::KO => LocaleCode::Ko,
            work_query::LocaleCode::KO_KR => LocaleCode::KoKr,
            work_query::LocaleCode::KHQ => LocaleCode::Khq,
            work_query::LocaleCode::KHQ_ML => LocaleCode::KhqMl,
            work_query::LocaleCode::SES => LocaleCode::Ses,
            work_query::LocaleCode::SES_ML => LocaleCode::SesMl,
            work_query::LocaleCode::NMG => LocaleCode::Nmg,
            work_query::LocaleCode::NMG_CM => LocaleCode::NmgCm,
            work_query::LocaleCode::KY => LocaleCode::Ky,
            work_query::LocaleCode::LAG => LocaleCode::Lag,
            work_query::LocaleCode::LAG_TZ => LocaleCode::LagTz,
            work_query::LocaleCode::LV => LocaleCode::Lv,
            work_query::LocaleCode::LV_LV => LocaleCode::LvLv,
            work_query::LocaleCode::LIR => LocaleCode::Lir,
            work_query::LocaleCode::LN => LocaleCode::Ln,
            work_query::LocaleCode::LN_CG => LocaleCode::LnCg,
            work_query::LocaleCode::LN_CD => LocaleCode::LnCd,
            work_query::LocaleCode::LT => LocaleCode::Lt,
            work_query::LocaleCode::LT_LT => LocaleCode::LtLt,
            work_query::LocaleCode::LU => LocaleCode::Lu,
            work_query::LocaleCode::LU_CD => LocaleCode::LuCd,
            work_query::LocaleCode::LUO => LocaleCode::Luo,
            work_query::LocaleCode::LUO_KE => LocaleCode::LuoKe,
            work_query::LocaleCode::LUY => LocaleCode::Luy,
            work_query::LocaleCode::LUY_KE => LocaleCode::LuyKe,
            work_query::LocaleCode::MK => LocaleCode::Mk,
            work_query::LocaleCode::MK_MK => LocaleCode::MkMk,
            work_query::LocaleCode::JMC => LocaleCode::Jmc,
            work_query::LocaleCode::JMC_TZ => LocaleCode::JmcTz,
            work_query::LocaleCode::MGH => LocaleCode::Mgh,
            work_query::LocaleCode::MGH_MZ => LocaleCode::MghMz,
            work_query::LocaleCode::KDE => LocaleCode::Kde,
            work_query::LocaleCode::KDE_TZ => LocaleCode::KdeTz,
            work_query::LocaleCode::MG => LocaleCode::Mg,
            work_query::LocaleCode::MG_MG => LocaleCode::MgMg,
            work_query::LocaleCode::MS => LocaleCode::Ms,
            work_query::LocaleCode::MS_BN => LocaleCode::MsBn,
            work_query::LocaleCode::MS_MY => LocaleCode::MsMy,
            work_query::LocaleCode::ML => LocaleCode::Ml,
            work_query::LocaleCode::ML_IN => LocaleCode::MlIn,
            work_query::LocaleCode::MT => LocaleCode::Mt,
            work_query::LocaleCode::MT_MT => LocaleCode::MtMt,
            work_query::LocaleCode::GV => LocaleCode::Gv,
            work_query::LocaleCode::GV_GB => LocaleCode::GvGb,
            work_query::LocaleCode::MR => LocaleCode::Mr,
            work_query::LocaleCode::MR_IN => LocaleCode::MrIn,
            work_query::LocaleCode::MAS => LocaleCode::Mas,
            work_query::LocaleCode::MAS_KE => LocaleCode::MasKe,
            work_query::LocaleCode::MAS_TZ => LocaleCode::MasTz,
            work_query::LocaleCode::MER => LocaleCode::Mer,
            work_query::LocaleCode::MER_KE => LocaleCode::MerKe,
            work_query::LocaleCode::MN => LocaleCode::Mn,
            work_query::LocaleCode::MFE => LocaleCode::Mfe,
            work_query::LocaleCode::MFE_MU => LocaleCode::MfeMu,
            work_query::LocaleCode::MUA => LocaleCode::Mua,
            work_query::LocaleCode::MUA_CM => LocaleCode::MuaCm,
            work_query::LocaleCode::NAQ => LocaleCode::Naq,
            work_query::LocaleCode::NAQ_NA => LocaleCode::NaqNa,
            work_query::LocaleCode::NE => LocaleCode::Ne,
            work_query::LocaleCode::NE_IN => LocaleCode::NeIn,
            work_query::LocaleCode::NE_NP => LocaleCode::NeNp,
            work_query::LocaleCode::SE => LocaleCode::Se,
            work_query::LocaleCode::SE_FI => LocaleCode::SeFi,
            work_query::LocaleCode::SE_NO => LocaleCode::SeNo,
            work_query::LocaleCode::SE_SE => LocaleCode::SeSe,
            work_query::LocaleCode::ND => LocaleCode::Nd,
            work_query::LocaleCode::ND_ZW => LocaleCode::NdZw,
            work_query::LocaleCode::NB => LocaleCode::Nb,
            work_query::LocaleCode::NB_NO => LocaleCode::NbNo,
            work_query::LocaleCode::NN => LocaleCode::Nn,
            work_query::LocaleCode::NN_NO => LocaleCode::NnNo,
            work_query::LocaleCode::NUS => LocaleCode::Nus,
            work_query::LocaleCode::NUS_SD => LocaleCode::NusSd,
            work_query::LocaleCode::NYN => LocaleCode::Nyn,
            work_query::LocaleCode::NYN_UG => LocaleCode::NynUg,
            work_query::LocaleCode::OR => LocaleCode::Or,
            work_query::LocaleCode::OR_IN => LocaleCode::OrIn,
            work_query::LocaleCode::OM => LocaleCode::Om,
            work_query::LocaleCode::OM_ET => LocaleCode::OmEt,
            work_query::LocaleCode::OM_KE => LocaleCode::OmKe,
            work_query::LocaleCode::PS => LocaleCode::Ps,
            work_query::LocaleCode::PS_AF => LocaleCode::PsAf,
            work_query::LocaleCode::FA => LocaleCode::Fa,
            work_query::LocaleCode::FA_AF => LocaleCode::FaAf,
            work_query::LocaleCode::FA_IR => LocaleCode::FaIr,
            work_query::LocaleCode::PL => LocaleCode::Pl,
            work_query::LocaleCode::PL_PL => LocaleCode::PlPl,
            work_query::LocaleCode::PT => LocaleCode::Pt,
            work_query::LocaleCode::PT_AO => LocaleCode::PtAo,
            work_query::LocaleCode::PT_BR => LocaleCode::PtBr,
            work_query::LocaleCode::PT_GW => LocaleCode::PtGw,
            work_query::LocaleCode::PT_MZ => LocaleCode::PtMz,
            work_query::LocaleCode::PT_PT => LocaleCode::PtPt,
            work_query::LocaleCode::PT_ST => LocaleCode::PtSt,
            work_query::LocaleCode::PA => LocaleCode::Pa,
            work_query::LocaleCode::PA_ARAB => LocaleCode::PaArab,
            work_query::LocaleCode::PA_ARAB_PK => LocaleCode::PaArabPk,
            work_query::LocaleCode::PA_GURU => LocaleCode::PaGuru,
            work_query::LocaleCode::PA_GURU_IN => LocaleCode::PaGuruIn,
            work_query::LocaleCode::RO => LocaleCode::Ro,
            work_query::LocaleCode::RO_MD => LocaleCode::RoMd,
            work_query::LocaleCode::RO_RO => LocaleCode::RoRo,
            work_query::LocaleCode::RM => LocaleCode::Rm,
            work_query::LocaleCode::RM_CH => LocaleCode::RmCh,
            work_query::LocaleCode::ROF => LocaleCode::Rof,
            work_query::LocaleCode::ROF_TZ => LocaleCode::RofTz,
            work_query::LocaleCode::RN => LocaleCode::Rn,
            work_query::LocaleCode::RN_BI => LocaleCode::RnBi,
            work_query::LocaleCode::RU => LocaleCode::Ru,
            work_query::LocaleCode::RU_MD => LocaleCode::RuMd,
            work_query::LocaleCode::RU_RU => LocaleCode::RuRu,
            work_query::LocaleCode::RU_UA => LocaleCode::RuUa,
            work_query::LocaleCode::RWK => LocaleCode::Rwk,
            work_query::LocaleCode::RWK_TZ => LocaleCode::RwkTz,
            work_query::LocaleCode::SAQ => LocaleCode::Saq,
            work_query::LocaleCode::SAQ_KE => LocaleCode::SaqKe,
            work_query::LocaleCode::SG => LocaleCode::Sg,
            work_query::LocaleCode::SG_CF => LocaleCode::SgCf,
            work_query::LocaleCode::SBP => LocaleCode::Sbp,
            work_query::LocaleCode::SBP_TZ => LocaleCode::SbpTz,
            work_query::LocaleCode::SA => LocaleCode::Sa,
            work_query::LocaleCode::GD => LocaleCode::Gd,
            work_query::LocaleCode::GD_GB => LocaleCode::GdGb,
            work_query::LocaleCode::SEH => LocaleCode::Seh,
            work_query::LocaleCode::SEH_MZ => LocaleCode::SehMz,
            work_query::LocaleCode::SR => LocaleCode::Sr,
            work_query::LocaleCode::SR_CYRL => LocaleCode::SrCyrl,
            work_query::LocaleCode::SR_CYRL_BA => LocaleCode::SrCyrlBa,
            work_query::LocaleCode::SR_CYRL_ME => LocaleCode::SrCyrlMe,
            work_query::LocaleCode::SR_CYRL_RS => LocaleCode::SrCyrlRs,
            work_query::LocaleCode::SR_LATN => LocaleCode::SrLatn,
            work_query::LocaleCode::SR_LATN_BA => LocaleCode::SrLatnBa,
            work_query::LocaleCode::SR_LATN_ME => LocaleCode::SrLatnMe,
            work_query::LocaleCode::SR_LATN_RS => LocaleCode::SrLatnRs,
            work_query::LocaleCode::KSB => LocaleCode::Ksb,
            work_query::LocaleCode::KSB_TZ => LocaleCode::KsbTz,
            work_query::LocaleCode::SN => LocaleCode::Sn,
            work_query::LocaleCode::SN_ZW => LocaleCode::SnZw,
            work_query::LocaleCode::II => LocaleCode::Ii,
            work_query::LocaleCode::II_CN => LocaleCode::IiCn,
            work_query::LocaleCode::SI => LocaleCode::Si,
            work_query::LocaleCode::SI_LK => LocaleCode::SiLk,
            work_query::LocaleCode::SK => LocaleCode::Sk,
            work_query::LocaleCode::SK_SK => LocaleCode::SkSk,
            work_query::LocaleCode::SL => LocaleCode::Sl,
            work_query::LocaleCode::SL_SI => LocaleCode::SlSi,
            work_query::LocaleCode::XOG => LocaleCode::Xog,
            work_query::LocaleCode::XOG_UG => LocaleCode::XogUg,
            work_query::LocaleCode::SO => LocaleCode::So,
            work_query::LocaleCode::SO_DJ => LocaleCode::SoDj,
            work_query::LocaleCode::SO_ET => LocaleCode::SoEt,
            work_query::LocaleCode::SO_KE => LocaleCode::SoKe,
            work_query::LocaleCode::SO_SO => LocaleCode::SoSo,
            work_query::LocaleCode::ES => LocaleCode::Es,
            work_query::LocaleCode::ES_AR => LocaleCode::EsAr,
            work_query::LocaleCode::ES_BO => LocaleCode::EsBo,
            work_query::LocaleCode::ES_CL => LocaleCode::EsCl,
            work_query::LocaleCode::ES_CO => LocaleCode::EsCo,
            work_query::LocaleCode::ES_CR => LocaleCode::EsCr,
            work_query::LocaleCode::ES_DO => LocaleCode::EsDo,
            work_query::LocaleCode::ES_EC => LocaleCode::EsEc,
            work_query::LocaleCode::ES_SV => LocaleCode::EsSv,
            work_query::LocaleCode::ES_GQ => LocaleCode::EsGq,
            work_query::LocaleCode::ES_GT => LocaleCode::EsGt,
            work_query::LocaleCode::ES_HN => LocaleCode::EsHn,
            work_query::LocaleCode::ES419 => LocaleCode::Es419,
            work_query::LocaleCode::ES_MX => LocaleCode::EsMx,
            work_query::LocaleCode::ES_NI => LocaleCode::EsNi,
            work_query::LocaleCode::ES_PA => LocaleCode::EsPa,
            work_query::LocaleCode::ES_PY => LocaleCode::EsPy,
            work_query::LocaleCode::ES_PE => LocaleCode::EsPe,
            work_query::LocaleCode::ES_PR => LocaleCode::EsPr,
            work_query::LocaleCode::ES_ES => LocaleCode::EsEs,
            work_query::LocaleCode::ES_US => LocaleCode::EsUs,
            work_query::LocaleCode::ES_UY => LocaleCode::EsUy,
            work_query::LocaleCode::ES_VE => LocaleCode::EsVe,
            work_query::LocaleCode::SW => LocaleCode::Sw,
            work_query::LocaleCode::SW_KE => LocaleCode::SwKe,
            work_query::LocaleCode::SW_TZ => LocaleCode::SwTz,
            work_query::LocaleCode::SV => LocaleCode::Sv,
            work_query::LocaleCode::SV_FI => LocaleCode::SvFi,
            work_query::LocaleCode::SV_SE => LocaleCode::SvSe,
            work_query::LocaleCode::GSW => LocaleCode::Gsw,
            work_query::LocaleCode::GSW_CH => LocaleCode::GswCh,
            work_query::LocaleCode::SHI => LocaleCode::Shi,
            work_query::LocaleCode::SHI_LATN => LocaleCode::ShiLatn,
            work_query::LocaleCode::SHI_LATN_MA => LocaleCode::ShiLatnMa,
            work_query::LocaleCode::SHI_TFNG => LocaleCode::ShiTfng,
            work_query::LocaleCode::SHI_TFNG_MA => LocaleCode::ShiTfngMa,
            work_query::LocaleCode::DAV => LocaleCode::Dav,
            work_query::LocaleCode::DAV_KE => LocaleCode::DavKe,
            work_query::LocaleCode::TG => LocaleCode::Tg,
            work_query::LocaleCode::TA => LocaleCode::Ta,
            work_query::LocaleCode::TA_IN => LocaleCode::TaIn,
            work_query::LocaleCode::TA_LK => LocaleCode::TaLk,
            work_query::LocaleCode::TWQ => LocaleCode::Twq,
            work_query::LocaleCode::TWQ_NE => LocaleCode::TwqNe,
            work_query::LocaleCode::MI => LocaleCode::Mi,
            work_query::LocaleCode::TE => LocaleCode::Te,
            work_query::LocaleCode::TE_IN => LocaleCode::TeIn,
            work_query::LocaleCode::TEO => LocaleCode::Teo,
            work_query::LocaleCode::TEO_KE => LocaleCode::TeoKe,
            work_query::LocaleCode::TEO_UG => LocaleCode::TeoUg,
            work_query::LocaleCode::TH => LocaleCode::Th,
            work_query::LocaleCode::TH_TH => LocaleCode::ThTh,
            work_query::LocaleCode::BO => LocaleCode::Bo,
            work_query::LocaleCode::BO_CN => LocaleCode::BoCn,
            work_query::LocaleCode::BO_IN => LocaleCode::BoIn,
            work_query::LocaleCode::TI => LocaleCode::Ti,
            work_query::LocaleCode::TI_ER => LocaleCode::TiEr,
            work_query::LocaleCode::TI_ET => LocaleCode::TiEt,
            work_query::LocaleCode::TO => LocaleCode::To,
            work_query::LocaleCode::TO_TO => LocaleCode::ToTo,
            work_query::LocaleCode::TR => LocaleCode::Tr,
            work_query::LocaleCode::TK => LocaleCode::Tk,
            work_query::LocaleCode::TR_TR => LocaleCode::TrTr,
            work_query::LocaleCode::TCH => LocaleCode::Tch,
            work_query::LocaleCode::UK => LocaleCode::Uk,
            work_query::LocaleCode::UK_UA => LocaleCode::UkUa,
            work_query::LocaleCode::UR => LocaleCode::Ur,
            work_query::LocaleCode::UR_IN => LocaleCode::UrIn,
            work_query::LocaleCode::UR_PK => LocaleCode::UrPk,
            work_query::LocaleCode::UG => LocaleCode::Ug,
            work_query::LocaleCode::UG_CN => LocaleCode::UgCn,
            work_query::LocaleCode::UZ => LocaleCode::Uz,
            work_query::LocaleCode::UZ_ARAB => LocaleCode::UzArab,
            work_query::LocaleCode::UZ_ARAB_AF => LocaleCode::UzArabAf,
            work_query::LocaleCode::UZ_CYRL => LocaleCode::UzCyrl,
            work_query::LocaleCode::UZ_CYRL_UZ => LocaleCode::UzCyrlUz,
            work_query::LocaleCode::UZ_LATN => LocaleCode::UzLatn,
            work_query::LocaleCode::UZ_LATN_UZ => LocaleCode::UzLatnUz,
            work_query::LocaleCode::VAI => LocaleCode::Vai,
            work_query::LocaleCode::VAI_LATN => LocaleCode::VaiLatn,
            work_query::LocaleCode::VAI_LATN_LR => LocaleCode::VaiLatnLr,
            work_query::LocaleCode::VAI_VAII => LocaleCode::VaiVaii,
            work_query::LocaleCode::VAI_VAII_LR => LocaleCode::VaiVaiiLr,
            work_query::LocaleCode::VAL => LocaleCode::Val,
            work_query::LocaleCode::VAL_ES => LocaleCode::ValEs,
            work_query::LocaleCode::CA_ES_VALENCIA => LocaleCode::CaEsValencia,
            work_query::LocaleCode::VI => LocaleCode::Vi,
            work_query::LocaleCode::VI_VN => LocaleCode::ViVn,
            work_query::LocaleCode::VUN => LocaleCode::Vun,
            work_query::LocaleCode::VUN_TZ => LocaleCode::VunTz,
            work_query::LocaleCode::CY => LocaleCode::Cy,
            work_query::LocaleCode::CY_GB => LocaleCode::CyGb,
            work_query::LocaleCode::WO => LocaleCode::Wo,
            work_query::LocaleCode::XH => LocaleCode::Xh,
            work_query::LocaleCode::YAV => LocaleCode::Yav,
            work_query::LocaleCode::YAV_CM => LocaleCode::YavCm,
            work_query::LocaleCode::YO => LocaleCode::Yo,
            work_query::LocaleCode::YO_NG => LocaleCode::YoNg,
            work_query::LocaleCode::DJE => LocaleCode::Dje,
            work_query::LocaleCode::DJE_NE => LocaleCode::DjeNe,
            work_query::LocaleCode::ZU => LocaleCode::Zu,
            work_query::LocaleCode::ZU_ZA => LocaleCode::ZuZa,
            work_query::LocaleCode::Other(_) => unreachable!(),
        }
    }
}
