ARG RUST_VERSION=1.62.1

FROM rust:${RUST_VERSION}

ENV NPM_VERSION=6.14.8
ENV N_VERSION=6.7.0
ENV NODE_VERSION=12.19.0
ENV ROLLUP_VERSION=2.28.2
ENV WASM_PACK_VERSION=0.9.1

ARG THOTH_GRAPHQL_API=http://graphql-api:8000
ARG THOTH_EXPORT_API=http://export-api:8181
ENV THOTH_GRAPHQL_API=${THOTH_GRAPHQL_API}
ENV THOTH_EXPORT_API=${THOTH_EXPORT_API}

WORKDIR /usr/src/thoth

# Expose thoth's default ports
EXPOSE 8080
EXPOSE 8000
EXPOSE 8181

# Install build dependencies
RUN apt-get update && apt-get -y install pkg-config npm
RUN npm install -g npm@${NPM_VERSION}
RUN npm install -g n@${N_VERSION}
RUN n ${NODE_VERSION}
RUN npm install -g rollup@${ROLLUP_VERSION}
RUN cargo install wasm-pack --version ${WASM_PACK_VERSION}

# Get source
COPY . .

# Compile WASM for debug
RUN wasm-pack build thoth-app/ \
  --target web \
  --debug
RUN rollup thoth-app/main.js \
  --format iife \
  --file thoth-app/pkg/thoth_app.js

# Build Thoth for debug
RUN cargo build
