-- Create the locale table
CREATE TABLE locale (
    locale_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    code TEXT NOT NULL CHECK (octet_length(code) >= 1),
    name TEXT NOT NULL CHECK (octet_length(name) >= 1)
);

-- Populate locale table with JSON data and English
INSERT INTO locale (locale_id, code, name)
VALUES
(uuid_generate_v4(), 'af', 'Afrikaans (af)'),
(uuid_generate_v4(), 'af-NA', 'Afrikaans (Namibia) (af-NA)'),
(uuid_generate_v4(), 'af-ZA', 'Afrikaans (South Africa) (af-ZA)'),
(uuid_generate_v4(), 'agq', 'Aghem (agq)'),
(uuid_generate_v4(), 'agq-CM', 'Aghem (Cameroon) (agq-CM)'),
(uuid_generate_v4(), 'ak', 'Akan (ak)'),
(uuid_generate_v4(), 'ak-GH', 'Akan (Ghana) (ak-GH)'),
(uuid_generate_v4(), 'sq', 'Albanian (sq)'),
(uuid_generate_v4(), 'sq-AL', 'Albanian (Albania) (sq-AL)'),
(uuid_generate_v4(), 'am', 'Amharic (am)'),
(uuid_generate_v4(), 'am-ET', 'Amharic (Ethiopia) (am-ET)'),
(uuid_generate_v4(), 'aig', 'Antigua and Barbuda Creole English'),
(uuid_generate_v4(), 'ar', 'Arabic (ar)'),
(uuid_generate_v4(), 'ar-DZ', 'Arabic (Algeria) (ar-DZ)'),
(uuid_generate_v4(), 'ar-BH', 'Arabic (Bahrain) (ar-BH)'),
(uuid_generate_v4(), 'ar-EG', 'Arabic (Egypt) (ar-EG)'),
(uuid_generate_v4(), 'ar-IQ', 'Arabic (Iraq) (ar-IQ)'),
(uuid_generate_v4(), 'ar-JO', 'Arabic (Jordan) (ar-JO)'),
(uuid_generate_v4(), 'ar-KW', 'Arabic (Kuwait) (ar-KW)'),
(uuid_generate_v4(), 'ar-LB', 'Arabic (Lebanon) (ar-LB)'),
(uuid_generate_v4(), 'ar-LY', 'Arabic (Libya) (ar-LY)'),
(uuid_generate_v4(), 'ar-MA', 'Arabic (Morocco) (ar-MA)'),
(uuid_generate_v4(), 'ar-OM', 'Arabic (Oman) (ar-OM)'),
(uuid_generate_v4(), 'ar-QA', 'Arabic (Qatar) (ar-QA)'),
(uuid_generate_v4(), 'ar-SA', 'Arabic (Saudi Arabia) (ar-SA)'),
(uuid_generate_v4(), 'ar-SD', 'Arabic (Sudan) (ar-SD)'),
(uuid_generate_v4(), 'ar-SY', 'Arabic (Syria) (ar-SY)'),
(uuid_generate_v4(), 'ar-TN', 'Arabic (Tunisia) (ar-TN)'),
(uuid_generate_v4(), 'ar-AE', 'Arabic (United Arab Emirates) (ar-AE)'),
(uuid_generate_v4(), 'ar-001', 'Arabic (World) (ar-001)'),
(uuid_generate_v4(), 'ar-YE', 'Arabic (Yemen) (ar-YE)'),
(uuid_generate_v4(), 'hy', 'Armenian (hy)'),
(uuid_generate_v4(), 'hy-AM', 'Armenian (Armenia) (hy-AM)'),
(uuid_generate_v4(), 'as', 'Assamese (as)'),
(uuid_generate_v4(), 'as-IN', 'Assamese (India) (as-IN)'),
(uuid_generate_v4(), 'ast', 'Asturian (ast)'),
(uuid_generate_v4(), 'ast-ES', 'Asturian (Spain) (ast-ES)'),
(uuid_generate_v4(), 'asa', 'Asu (asa)'),
(uuid_generate_v4(), 'asa-TZ', 'Asu (Tanzania) (asa-TZ)'),
(uuid_generate_v4(), 'az', 'Azerbaijani (az)'),
(uuid_generate_v4(), 'az-Cyrl', 'Azerbaijani (Cyrillic) (az-Cyrl)'),
(uuid_generate_v4(), 'az-Cyrl-AZ', 'Azerbaijani (Cyrillic, Azerbaijan) (az-Cyrl-AZ)'),
(uuid_generate_v4(), 'az-Latn', 'Azerbaijani (Latin) (az-Latn)'),
(uuid_generate_v4(), 'az-Latn-AZ', 'Azerbaijani (Latin, Azerbaijan) (az-Latn-AZ)'),
(uuid_generate_v4(), 'ksf', 'Bafia (ksf)'),
(uuid_generate_v4(), 'ksf-CM', 'Bafia (Cameroon) (ksf-CM)'),
(uuid_generate_v4(), 'bah', 'Bahamas Creole English'),
(uuid_generate_v4(), 'bm', 'Bambara (bm)'),
(uuid_generate_v4(), 'bm-ML', 'Bambara (Mali) (bm-ML)'),
(uuid_generate_v4(), 'bas', 'Basaa (bas)'),
(uuid_generate_v4(), 'bas-CM', 'Basaa (Cameroon) (bas-CM)'),
(uuid_generate_v4(), 'eu', 'Basque (eu)'),
(uuid_generate_v4(), 'eu-ES', 'Basque (Spain) (eu-ES)'),
(uuid_generate_v4(), 'be', 'Belarusian (be)'),
(uuid_generate_v4(), 'be-BY', 'Belarusian (Belarus) (be-BY)'),
(uuid_generate_v4(), 'bem', 'Bemba (bem)'),
(uuid_generate_v4(), 'bem-ZM', 'Bemba (Zambia) (bem-ZM)'),
(uuid_generate_v4(), 'bez', 'Bena (bez)'),
(uuid_generate_v4(), 'bez-TZ', 'Bena (Tanzania) (bez-TZ)'),
(uuid_generate_v4(), 'bn', 'Bengali (bn)'),
(uuid_generate_v4(), 'bn-BD', 'Bengali (Bangladesh) (bn-BD)'),
(uuid_generate_v4(), 'bn-IN', 'Bengali (India) (bn-IN)'),
(uuid_generate_v4(), 'brx', 'Bodo (brx)'),
(uuid_generate_v4(), 'brx-IN', 'Bodo (India) (brx-IN)'),
(uuid_generate_v4(), 'bs', 'Bosnian (bs)'),
(uuid_generate_v4(), 'bs-BA', 'Bosnian (Bosnia and Herzegovina) (bs-BA)'),
(uuid_generate_v4(), 'br', 'Breton (br)'),
(uuid_generate_v4(), 'br-FR', 'Breton (France) (br-FR)'),
(uuid_generate_v4(), 'bg', 'Bulgarian (bg)'),
(uuid_generate_v4(), 'bg-BG', 'Bulgarian (Bulgaria) (bg-BG)'),
(uuid_generate_v4(), 'my', 'Burmese (my)'),
(uuid_generate_v4(), 'my-MM', 'Burmese (Myanmar [Burma]) (my-MM)'),
(uuid_generate_v4(), 'ca', 'Catalan (ca)'),
(uuid_generate_v4(), 'ca-ES', 'Catalan (Spain) (ca-ES)'),
(uuid_generate_v4(), 'ckb', 'Central Kurdish (ckb)'),
(uuid_generate_v4(), 'kmr', 'Northern Kurdish (kmr)'),
(uuid_generate_v4(), 'sdh', 'Southern Kurdish (sdh)'),
(uuid_generate_v4(), 'tzm', 'Central Morocco Tamazight (tzm)'),
(uuid_generate_v4(), 'tzm-Latn', 'Central Morocco Tamazight (Latin) (tzm-Latn)'),
(uuid_generate_v4(), 'tzm-Latn-MA', 'Central Morocco Tamazight (Latin, Morocco) (tzm-Latn-MA) '),
(uuid_generate_v4(), 'chr', 'Cherokee (chr)'),
(uuid_generate_v4(), 'chr-US', 'Cherokee (United States) (chr-US)'),
(uuid_generate_v4(), 'cgg', 'Chiga (cgg)'),
(uuid_generate_v4(), 'cgg-UG', 'Chiga (Uganda) (cgg-UG)'),
(uuid_generate_v4(), 'zh', 'Chinese (zh)'),
(uuid_generate_v4(), 'zh-Hans', 'Chinese (Simplified) (zh-Hans)'),
(uuid_generate_v4(), 'zh-CN', 'Chinese (Simplified, China) (zh-CN)'),
(uuid_generate_v4(), 'zh-Hans-CN', 'Chinese (Simplified, China) (zh-Hans-CN)'),
(uuid_generate_v4(), 'zh-Hans-HK', 'Chinese (Simplified, Hong Kong SAR China) (zh-Hans-HK)'),
(uuid_generate_v4(), 'zh-Hans-MO', 'Chinese (Simplified, Macau SAR China) (zh-Hans-MO) '),
(uuid_generate_v4(), 'zh-Hans-SG', 'Chinese (Simplified, Singapore) (zh-Hans-SG)'),
(uuid_generate_v4(), 'zh-Hant', 'Chinese (Traditional) (zh-Hant)'),
(uuid_generate_v4(), 'zh-Hant-HK', 'Chinese (Traditional, Hong Kong SAR China) (zh-Hant-HK) '),
(uuid_generate_v4(), 'zh-Hant-MO', 'Chinese (Traditional, Macau SAR China) (zh-Hant-MO) '),
(uuid_generate_v4(), 'zh-Hant-TW', 'Chinese (Traditional, Taiwan) (zh-Hant-TW)'),
(uuid_generate_v4(), 'swc', 'Congo Swahili (swc)'),
(uuid_generate_v4(), 'swc-CD', 'Congo Swahili (Congo - Kinshasa) (swc-CD)'),
(uuid_generate_v4(), 'kw', 'Cornish (kw)'),
(uuid_generate_v4(), 'kw-GB', 'Cornish (United Kingdom) (kw-GB)'),
(uuid_generate_v4(), 'hr', 'Croatian (hr)'),
(uuid_generate_v4(), 'hr-HR', 'Croatian (Croatia) (hr-HR)'),
(uuid_generate_v4(), 'cs', 'Czech (cs)'),
(uuid_generate_v4(), 'cs-CZ', 'Czech (Czech Republic) (cs-CZ)'),
(uuid_generate_v4(), 'da', 'Danish (da)'),
(uuid_generate_v4(), 'da-DK', 'Danish (Denmark) (da-DK)'),
(uuid_generate_v4(), 'dua', 'Duala (dua)'),
(uuid_generate_v4(), 'dua-CM', 'Duala (Cameroon) (dua-CM)'),
(uuid_generate_v4(), 'dv', 'Dhivehi (Maldives)'),
(uuid_generate_v4(), 'nl', 'Dutch (nl)'),
(uuid_generate_v4(), 'nl-AW', 'Dutch (Aruba) (nl-AW)'),
(uuid_generate_v4(), 'nl-BE', 'Dutch (Belgium) (nl-BE)'),
(uuid_generate_v4(), 'nl-CW', 'Dutch (Curaçao) (nl-CW)'),
(uuid_generate_v4(), 'nl-NL', 'Dutch (Netherlands) (nl-NL)'),
(uuid_generate_v4(), 'nl-SX', 'Dutch (Sint Maarten) (nl-SX)'),
(uuid_generate_v4(), 'ebu', 'Embu (ebu)'),
(uuid_generate_v4(), 'ebu-KE', 'Embu (Kenya) (ebu-KE)'),
(uuid_generate_v4(), 'en', 'English (en)'),
(uuid_generate_v4(), 'en-AI', 'English (Anguilla) (en-AI)'),
(uuid_generate_v4(), 'en-AS', 'English (American Samoa) (en-AS)'),
(uuid_generate_v4(), 'en-AU', 'English (Australia) (en-AU)'),
(uuid_generate_v4(), 'en-AT', 'English (Austria) (en-AT)'),
(uuid_generate_v4(), 'en-BB', 'English (Barbados) (en-BB)'),
(uuid_generate_v4(), 'en-BE', 'English (Belgium) (en-BE)'),
(uuid_generate_v4(), 'en-BZ', 'English (Belize) (en-BZ)'),
(uuid_generate_v4(), 'en-BM', 'English (Bermuda) (en-BM)'),
(uuid_generate_v4(), 'en-BW', 'English (Botswana) (en-BW)'),
(uuid_generate_v4(), 'en-IO', 'English (British Indian Ocean Territory) (en-IO)'),
(uuid_generate_v4(), 'en-BI', 'English (Burundi) (en-BI)'),
(uuid_generate_v4(), 'en-CM', 'English (Cameroon) (en-CM)'),
(uuid_generate_v4(), 'en-CA', 'English (Canada) (en-CA)'),
(uuid_generate_v4(), 'en-KY', 'English (Cayman Islands) (en-KY)'),
(uuid_generate_v4(), 'en-CX', 'English (Christmas Island) (en-CX)'),
(uuid_generate_v4(), 'en-CC', 'English (Cocos [Keeling] Islands) (en-CC)'),
(uuid_generate_v4(), 'en-CK', 'English (Cook Islands) (en-CK)'),
(uuid_generate_v4(), 'en-CY', 'English (Cyprus) (en-CY)'),
(uuid_generate_v4(), 'en-DK', 'English (Denmark) (en-DK)'),
(uuid_generate_v4(), 'en-DG', 'English (Diego Garcia) (en-DG)'),
(uuid_generate_v4(), 'en-DM', 'English (Dominica) (en-DM)'),
(uuid_generate_v4(), 'en-EG', 'English (Egypt) (en-EG)'),
(uuid_generate_v4(), 'en-ER', 'English (Eritrea) (en-ER)'),
(uuid_generate_v4(), 'en-EU', 'English (Europe) (en-EU)'),
(uuid_generate_v4(), 'en-FK', 'English (Falkland Islands) (en-FK)'),
(uuid_generate_v4(), 'en-FJ', 'English (Fiji) (en-FJ)'),
(uuid_generate_v4(), 'en-FI', 'English (Finland) (en-FI)'),
(uuid_generate_v4(), 'en-GM', 'English (Gambia) (en-GM)'),
(uuid_generate_v4(), 'en-DE', 'English (Germany) (en-DE)'),
(uuid_generate_v4(), 'en-GH', 'English (Ghana) (en-GH)'),
(uuid_generate_v4(), 'en-GI', 'English (Gibraltar) (en-GI)'),
(uuid_generate_v4(), 'en-GD', 'English (Grenada) (en-GD)'),
(uuid_generate_v4(), 'en-GU', 'English (Guam) (en-GU)'),
(uuid_generate_v4(), 'en-GG', 'English (Guernsey) (en-GG)'),
(uuid_generate_v4(), 'en-GY', 'English (Guyana) (en-GY)'),
(uuid_generate_v4(), 'en-HK', 'English (Hong Kong SAR China) (en-HK)'),
(uuid_generate_v4(), 'en-IN', 'English (India) (en-IN)'),
(uuid_generate_v4(), 'en-IE', 'English (Ireland) (en-IE)'),
(uuid_generate_v4(), 'en-IM', 'English (Isle of Man) (en-IM)'),
(uuid_generate_v4(), 'en-IL', 'English (Israel) (en-IL)'),
(uuid_generate_v4(), 'en-JM', 'English (Jamaica) (en-JM)'),
(uuid_generate_v4(), 'en-JE', 'English (Jersey) (en-JE)'),
(uuid_generate_v4(), 'en-KE', 'English (Kenya) (en-KE)'),
(uuid_generate_v4(), 'en-KI', 'English (Kiribati) (en-KI)'),
(uuid_generate_v4(), 'en-KW', 'English (Kuwait) (en-KW)'),
(uuid_generate_v4(), 'en-LS', 'English (Lesotho) (en-LS)'),
(uuid_generate_v4(), 'en-MO', 'English (Macao SAR China) (en-MO)'),
(uuid_generate_v4(), 'en-MG', 'English (Madagascar) (en-MG)'),
(uuid_generate_v4(), 'en-MW', 'English (Malawi) (en-MW)'),
(uuid_generate_v4(), 'en-MY', 'English (Malaysia) (en-MY)'),
(uuid_generate_v4(), 'en-MT', 'English (Malta) (en-MT)'),
(uuid_generate_v4(), 'en-MH', 'English (Marshall Islands) (en-MH)'),
(uuid_generate_v4(), 'en-MU', 'English (Mauritius) (en-MU)'),
(uuid_generate_v4(), 'en-FM', 'English (Micronesia) (en-FM)'),
(uuid_generate_v4(), 'en-MS', 'English (Montserrat) (en-MS)'),
(uuid_generate_v4(), 'en-NA', 'English (Namibia) (en-NA)'),
(uuid_generate_v4(), 'en-NR', 'English (Nauru) (en-NR)'),
(uuid_generate_v4(), 'en-NL', 'English (Netherlands) (en-NL)'),
(uuid_generate_v4(), 'en-NZ', 'English (New Zealand) (en-NZ)'),
(uuid_generate_v4(), 'en-NG', 'English (Nigeria) (en-NG)'),
(uuid_generate_v4(), 'en-NU', 'English (Niue) (en-NU)'),
(uuid_generate_v4(), 'en-NF', 'English (Norfolk Island) (en-NF)'),
(uuid_generate_v4(), 'en-MP', 'English (Northern Mariana Islands) (en-MP)'),
(uuid_generate_v4(), 'en-NO', 'English (Norway) (en-NO)'),
(uuid_generate_v4(), 'en-PA', 'English (Panama) (en-PA)'),
(uuid_generate_v4(), 'en-PK', 'English (Pakistan) (en-PK)'),
(uuid_generate_v4(), 'en-PW', 'English (Palau) (en-PW)'),
(uuid_generate_v4(), 'en-PG', 'English (Papua New Guinea) (en-PG)'),
(uuid_generate_v4(), 'en-PH', 'English (Philippines) (en-PH)'),
(uuid_generate_v4(), 'en-PN', 'English (Pitcairn Islands) (en-PN)'),
(uuid_generate_v4(), 'en-PR', 'English (Puerto Rico) (en-PR)'),
(uuid_generate_v4(), 'en-RW', 'English (Rwanda) (en-RW)'),
(uuid_generate_v4(), 'en-WS', 'English (Samoa) (en-WS)'),
(uuid_generate_v4(), 'en-SA', 'English (Saudi Arabia) (en-SA)'),
(uuid_generate_v4(), 'en-SC', 'English (Seychelles) (en-SC)'),
(uuid_generate_v4(), 'en-SL', 'English (Sierra Leone) (en-SL)'),
(uuid_generate_v4(), 'en-SG', 'English (Singapore) (en-SG)'),
(uuid_generate_v4(), 'en-SX', 'English (Sint Maarten) (en-SX)'),
(uuid_generate_v4(), 'en-SI', 'English (Slovenia) (en-SI)'),
(uuid_generate_v4(), 'en-SB', 'English (Solomon Islands) (en-SB)'),
(uuid_generate_v4(), 'en-SS', 'English (South Sudan) (en-SS)'),
(uuid_generate_v4(), 'en-SH', 'English (St Helena) (en-SH)'),
(uuid_generate_v4(), 'en-KN', 'English (St Kitts & Nevis) (en-KN)'),
(uuid_generate_v4(), 'en-LC', 'English (St Lucia) (en-LC)'),
(uuid_generate_v4(), 'svc', 'Vincentian Creole English'),
(uuid_generate_v4(), 'vic', 'Virgin Islands Creole English'),
(uuid_generate_v4(), 'en-SD', 'English (Sudan) (en-SD)'),
(uuid_generate_v4(), 'en-SZ', 'English (Swaziland) (en-SZ)'),
(uuid_generate_v4(), 'en-SE', 'English (Sweden) (en-SE)'),
(uuid_generate_v4(), 'en-CH', 'English (Switzerland) (en-CH)'),
(uuid_generate_v4(), 'en-TZ', 'English (Tanzania) (en-TZ)'),
(uuid_generate_v4(), 'en-TK', 'English (Tokelau) (en-TK)'),
(uuid_generate_v4(), 'en-TO', 'English (Tonga) (en-TO)'),
(uuid_generate_v4(), 'en-TT', 'English (Trinidad and Tobago) (en-TT)'),
(uuid_generate_v4(), 'en-TV', 'English (Tuvalu) (en-TV)'),
(uuid_generate_v4(), 'en-ZA', 'English (South Africa) (en-ZA)'),
(uuid_generate_v4(), 'en-AE', 'English (U.A.E.) (en-AE)'),
(uuid_generate_v4(), 'en-UM', 'English (U.S. Minor Outlying Islands) (en-UM)'),
(uuid_generate_v4(), 'en-VI', 'English (U.S. Virgin Islands) (en-VI)'),
(uuid_generate_v4(), 'en-US-POSIX', 'English (U.S., Computer) (en-US-POSIX)'),
(uuid_generate_v4(), 'en-UG', 'English (Uganda) (en-UG)'),
(uuid_generate_v4(), 'en-GB', 'English (United Kingdom) (en-GB)'),
(uuid_generate_v4(), 'en-US', 'English (United States) (en-US)'),
(uuid_generate_v4(), 'en-VU', 'English (Vanuatu) (en-VU)'),
(uuid_generate_v4(), 'en-ZM', 'English (Zambia) (en-ZM)'),
(uuid_generate_v4(), 'en-ZW', 'English (Zimbabwe) (en-ZW)'),
(uuid_generate_v4(), 'eo', 'Esperanto (eo)'),
(uuid_generate_v4(), 'et', 'Estonian (et)'),
(uuid_generate_v4(), 'et-EE', 'Estonian (Estonia) (et-EE)'),
(uuid_generate_v4(), 'ee', 'Ewe (ee)'),
(uuid_generate_v4(), 'ee-GH', 'Ewe (Ghana) (ee-GH)'),
(uuid_generate_v4(), 'ee-TG', 'Ewe (Togo) (ee-TG)'),
(uuid_generate_v4(), 'ewo', 'Ewondo (ewo)'),
(uuid_generate_v4(), 'ewo-CM', 'Ewondo (Cameroon) (ewo-CM)'),
(uuid_generate_v4(), 'fo', 'Faroese (fo)'),
(uuid_generate_v4(), 'fo-FO', 'Faroese (Faroe Islands) (fo-FO)'),
(uuid_generate_v4(), 'fil', 'Filipino (fil)'),
(uuid_generate_v4(), 'fil-PH', 'Filipino (Philippines) (fil-PH)'),
(uuid_generate_v4(), 'fi', 'Finnish (fi)'),
(uuid_generate_v4(), 'fi-FI', 'Finnish (Finland) (fi-FI)'),
(uuid_generate_v4(), 'fr', 'French (fr)'),
(uuid_generate_v4(), 'fr-BE', 'French (Belgium) (fr-BE)'),
(uuid_generate_v4(), 'fr-BJ', 'French (Benin) (fr-BJ)'),
(uuid_generate_v4(), 'fr-BF', 'French (Burkina Faso) (fr-BF)'),
(uuid_generate_v4(), 'fr-BI', 'French (Burundi) (fr-BI)'),
(uuid_generate_v4(), 'fr-CM', 'French (Cameroon) (fr-CM)'),
(uuid_generate_v4(), 'fr-CA', 'French (Canada) (fr-CA)'),
(uuid_generate_v4(), 'fr-CF', 'French (Central African Republic) (fr-CF)'),
(uuid_generate_v4(), 'fr-TD', 'French (Chad) (fr-TD)'),
(uuid_generate_v4(), 'fr-KM', 'French (Comoros) (fr-KM)'),
(uuid_generate_v4(), 'fr-CG', 'French (Congo - Brazzaville) (fr-CG)'),
(uuid_generate_v4(), 'fr-CD', 'French (Congo - Kinshasa) (fr-CD)'),
(uuid_generate_v4(), 'fr-CI', 'French (Côte d’Ivoire) (fr-CI)'),
(uuid_generate_v4(), 'fr-DJ', 'French (Djibouti) (fr-DJ)'),
(uuid_generate_v4(), 'fr-GQ', 'French (Equatorial Guinea) (fr-GQ)'),
(uuid_generate_v4(), 'fr-FR', 'French (France) (fr-FR)'),
(uuid_generate_v4(), 'fr-GF', 'French (French Guiana) (fr-GF)'),
(uuid_generate_v4(), 'fr-GA', 'French (Gabon) (fr-GA)'),
(uuid_generate_v4(), 'fr-GP', 'French (Guadeloupe) (fr-GP)'),
(uuid_generate_v4(), 'fr-GN', 'French (Guinea) (fr-GN)'),
(uuid_generate_v4(), 'fr-LU', 'French (Luxembourg) (fr-LU)'),
(uuid_generate_v4(), 'fr-MG', 'French (Madagascar) (fr-MG)'),
(uuid_generate_v4(), 'fr-ML', 'French (Mali) (fr-ML)'),
(uuid_generate_v4(), 'fr-MQ', 'French (Martinique) (fr-MQ)'),
(uuid_generate_v4(), 'fr-YT', 'French (Mayotte) (fr-YT)'),
(uuid_generate_v4(), 'fr-MC', 'French (Monaco) (fr-MC)'),
(uuid_generate_v4(), 'fr-NE', 'French (Niger) (fr-NE)'),
(uuid_generate_v4(), 'fr-RW', 'French (Rwanda) (fr-RW)'),
(uuid_generate_v4(), 'fr-RE', 'French (Réunion) (fr-RE)'),
(uuid_generate_v4(), 'fr-BL', 'French (Saint Barthélemy) (fr-BL)'),
(uuid_generate_v4(), 'fr-MF', 'French (Saint Martin) (fr-MF)'),
(uuid_generate_v4(), 'fr-MU', 'French (Mauritius) (fr-MU)'),
(uuid_generate_v4(), 'fr-SN', 'French (Senegal) (fr-SN)'),
(uuid_generate_v4(), 'fr-CH', 'French (Switzerland) (fr-CH)'),
(uuid_generate_v4(), 'fr-TG', 'French (Togo) (fr-TG)'),
(uuid_generate_v4(), 'ff', 'Fulah (ff)'),
(uuid_generate_v4(), 'ff-SN', 'Fulah (Senegal) (ff-SN)'),
(uuid_generate_v4(), 'gl', 'Galician (gl)'),
(uuid_generate_v4(), 'gl-ES', 'Galician (Spain) (gl-ES)'),
(uuid_generate_v4(), 'lao', 'Laotian (Laos) (lao)'),
(uuid_generate_v4(), 'lg', 'Ganda (lg)'),
(uuid_generate_v4(), 'lg-UG', 'Ganda (Uganda) (lg-UG)'),
(uuid_generate_v4(), 'ka', 'Georgian (ka)'),
(uuid_generate_v4(), 'ka-GE', 'Georgian (Georgia) (ka-GE)'),
(uuid_generate_v4(), 'de', 'German (de)'),
(uuid_generate_v4(), 'de-AT', 'German (Austria) (de-AT)'),
(uuid_generate_v4(), 'de-BE', 'German (Belgium) (de-BE)'),
(uuid_generate_v4(), 'de-DE', 'German (Germany) (de-DE)'),
(uuid_generate_v4(), 'de-LI', 'German (Liechtenstein) (de-LI)'),
(uuid_generate_v4(), 'de-LU', 'German (Luxembourg) (de-LU)'),
(uuid_generate_v4(), 'de-CH', 'German (Switzerland) (de-CH)'),
(uuid_generate_v4(), 'el', 'Greek (el)'),
(uuid_generate_v4(), 'el-CY', 'Greek (Cyprus) (el-CY)'),
(uuid_generate_v4(), 'el-GR', 'Greek (Greece) (el-GR)'),
(uuid_generate_v4(), 'gu', 'Gujarati (gu)'),
(uuid_generate_v4(), 'gu-IN', 'Gujarati (India) (gu-IN)'),
(uuid_generate_v4(), 'guz', 'Gusii (guz)'),
(uuid_generate_v4(), 'guz-KE', 'Gusii (Kenya) (guz-KE)'),
(uuid_generate_v4(), 'ha', 'Hausa (ha)'),
(uuid_generate_v4(), 'ha-Latn', 'Hausa (Latin) (ha-Latn)'),
(uuid_generate_v4(), 'ha-Latn-GH', 'Hausa (Latin, Ghana) (ha-Latn-GH)'),
(uuid_generate_v4(), 'ha-Latn-NE', 'Hausa (Latin, Niger) (ha-Latn-NE)'),
(uuid_generate_v4(), 'ha-Latn-NG', 'Hausa (Latin, Nigeria) (ha-Latn-NG)'),
(uuid_generate_v4(), 'haw', 'Hawaiian (haw)'),
(uuid_generate_v4(), 'haw-US', 'Hawaiian (United States) (haw-US)'),
(uuid_generate_v4(), 'he', 'Hebrew (he)'),
(uuid_generate_v4(), 'he-IL', 'Hebrew (Israel) (he-IL)'),
(uuid_generate_v4(), 'hi', 'Hindi (hi)'),
(uuid_generate_v4(), 'hi-IN', 'Hindi (India) (hi-IN)'),
(uuid_generate_v4(), 'hu', 'Hungarian (hu)'),
(uuid_generate_v4(), 'hu-HU', 'Hungarian (Hungary) (hu-HU)'),
(uuid_generate_v4(), 'is', 'Icelandic (is)'),
(uuid_generate_v4(), 'is-IS', 'Icelandic (Iceland) (is-IS)'),
(uuid_generate_v4(), 'ig', 'Igbo (ig)'),
(uuid_generate_v4(), 'ig-NG', 'Igbo (Nigeria) (ig-NG)'),
(uuid_generate_v4(), 'smn', 'Inari Sami'),
(uuid_generate_v4(), 'smn-FI', 'Inari Sami (Finland)'),
(uuid_generate_v4(), 'id', 'Indonesian (id)'),
(uuid_generate_v4(), 'id-ID', 'Indonesian (Indonesia) (id-ID)'),
(uuid_generate_v4(), 'ga', 'Irish (ga)'),
(uuid_generate_v4(), 'ga-IE', 'Irish (Ireland) (ga-IE)'),
(uuid_generate_v4(), 'it', 'Italian (it)'),
(uuid_generate_v4(), 'it-IT', 'Italian (Italy) (it-IT)'),
(uuid_generate_v4(), 'it-CH', 'Italian (Switzerland) (it-CH)'),
(uuid_generate_v4(), 'ja', 'Japanese (ja)'),
(uuid_generate_v4(), 'ja-JP', 'Japanese (Japan) (ja-JP)'),
(uuid_generate_v4(), 'dyo', 'Jola-Fonyi (dyo)'),
(uuid_generate_v4(), 'dyo-SN', 'Jola-Fonyi (Senegal) (dyo-SN)'),
(uuid_generate_v4(), 'kea', 'Kabuverdianu (kea)'),
(uuid_generate_v4(), 'kea-CV', 'Kabuverdianu (Cape Verde) (kea-CV)'),
(uuid_generate_v4(), 'kab', 'Kabyle (kab)'),
(uuid_generate_v4(), 'kab-DZ', 'Kabyle (Algeria) (kab-DZ)'),
(uuid_generate_v4(), 'kl', 'Kalaallisut (kl)'),
(uuid_generate_v4(), 'kl-GL', 'Kalaallisut (Greenland) (kl-GL)'),
(uuid_generate_v4(), 'kln', 'Kalenjin (kln)'),
(uuid_generate_v4(), 'kln-KE', 'Kalenjin (Kenya) (kln-KE)'),
(uuid_generate_v4(), 'kam', 'Kamba (kam)'),
(uuid_generate_v4(), 'kam-KE', 'Kamba (Kenya) (kam-KE)'),
(uuid_generate_v4(), 'kn', 'Kannada (kn)'),
(uuid_generate_v4(), 'kn-IN', 'Kannada (India) (kn-IN)'),
(uuid_generate_v4(), 'kaa', 'Kara-Kalpak (kaa)'),
(uuid_generate_v4(), 'kk', 'Kazakh (kk)'),
(uuid_generate_v4(), 'kk-Cyrl', 'Kazakh (Cyrillic) (kk-Cyrl)'),
(uuid_generate_v4(), 'kk-Cyrl-KZ', 'Kazakh (Cyrillic, Kazakhstan) (kk-Cyrl-KZ)'),
(uuid_generate_v4(), 'km', 'Khmer (km)'),
(uuid_generate_v4(), 'km-KH', 'Khmer (Cambodia) (km-KH)'),
(uuid_generate_v4(), 'ki', 'Kikuyu (ki)'),
(uuid_generate_v4(), 'ki-KE', 'Kikuyu (Kenya) (ki-KE)'),
(uuid_generate_v4(), 'rw', 'Kinyarwanda (rw)'),
(uuid_generate_v4(), 'rw-RW', 'Kinyarwanda (Rwanda) (rw-RW)'),
(uuid_generate_v4(), 'kok', 'Konkani (kok)'),
(uuid_generate_v4(), 'kok-IN', 'Konkani (India) (kok-IN)'),
(uuid_generate_v4(), 'ko', 'Korean (ko)'),
(uuid_generate_v4(), 'ko-KR', 'Korean (South Korea) (ko-KR)'),
(uuid_generate_v4(), 'khq', 'Koyra Chiini (khq)'),
(uuid_generate_v4(), 'khq-ML', 'Koyra Chiini (Mali) (khq-ML)'),
(uuid_generate_v4(), 'ses', 'Koyraboro Senni (ses)'),
(uuid_generate_v4(), 'ses-ML', 'Koyraboro Senni (Mali) (ses-ML)'),
(uuid_generate_v4(), 'nmg', 'Kwasio (nmg)'),
(uuid_generate_v4(), 'nmg-CM', 'Kwasio (Cameroon) (nmg-CM)'),
(uuid_generate_v4(), 'ky', 'Kyrgyz (ky)'),
(uuid_generate_v4(), 'lag', 'Langi (lag)'),
(uuid_generate_v4(), 'lag-TZ', 'Langi (Tanzania) (lag-TZ)'),
(uuid_generate_v4(), 'lv', 'Latvian (lv)'),
(uuid_generate_v4(), 'lv-LV', 'Latvian (Latvia) (lv-LV)'),
(uuid_generate_v4(), 'lir', 'Liberian English'),
(uuid_generate_v4(), 'ln', 'Lingala (ln)'),
(uuid_generate_v4(), 'ln-CG', 'Lingala (Congo - Brazzaville) (ln-CG)'),
(uuid_generate_v4(), 'ln-CD', 'Lingala (Congo - Kinshasa) (ln-CD)'),
(uuid_generate_v4(), 'lt', 'Lithuanian (lt)'),
(uuid_generate_v4(), 'lt-LT', 'Lithuanian (Lithuania) (lt-LT)'),
(uuid_generate_v4(), 'lu', 'Luba-Katanga (lu)'),
(uuid_generate_v4(), 'lu-CD', 'Luba-Katanga (Congo - Kinshasa) (lu-CD)'),
(uuid_generate_v4(), 'luo', 'Luo (luo)'),
(uuid_generate_v4(), 'luo-KE', 'Luo (Kenya) (luo-KE)'),
(uuid_generate_v4(), 'luy', 'Luyia (luy)'),
(uuid_generate_v4(), 'luy-KE', 'Luyia (Kenya) (luy-KE)'),
(uuid_generate_v4(), 'mk', 'Macedonian (mk)'),
(uuid_generate_v4(), 'mk-MK', 'Macedonian (Macedonia) (mk-MK)'),
(uuid_generate_v4(), 'jmc', 'Machame (jmc)'),
(uuid_generate_v4(), 'jmc-TZ', 'Machame (Tanzania) (jmc-TZ)'),
(uuid_generate_v4(), 'mgh', 'Makhuwa-Meetto (mgh)'),
(uuid_generate_v4(), 'mgh-MZ', 'Makhuwa-Meetto (Mozambique) (mgh-MZ)'),
(uuid_generate_v4(), 'kde', 'Makonde (kde)'),
(uuid_generate_v4(), 'kde-TZ', 'Makonde (Tanzania) (kde-TZ)'),
(uuid_generate_v4(), 'mg', 'Malagasy (mg)'),
(uuid_generate_v4(), 'mg-MG', 'Malagasy (Madagascar) (mg-MG)'),
(uuid_generate_v4(), 'ms', 'Malay (ms)'),
(uuid_generate_v4(), 'ms-BN', 'Malay (Brunei) (ms-BN)'),
(uuid_generate_v4(), 'ms-MY', 'Malay (Malaysia) (ms-MY)'),
(uuid_generate_v4(), 'ml', 'Malayalam (ml)'),
(uuid_generate_v4(), 'ml-IN', 'Malayalam (India) (ml-IN)'),
(uuid_generate_v4(), 'mt', 'Maltese (mt)'),
(uuid_generate_v4(), 'mt-MT', 'Maltese (Malta) (mt-MT)'),
(uuid_generate_v4(), 'gv', 'Manx (gv)'),
(uuid_generate_v4(), 'gv-GB', 'Manx (United Kingdom) (gv-GB)'),
(uuid_generate_v4(), 'mr', 'Marathi (mr)'),
(uuid_generate_v4(), 'mr-IN', 'Marathi (India) (mr-IN)'),
(uuid_generate_v4(), 'mas', 'Masai (mas)'),
(uuid_generate_v4(), 'mas-KE', 'Masai (Kenya) (mas-KE)'),
(uuid_generate_v4(), 'mas-TZ', 'Masai (Tanzania) (mas-TZ)'),
(uuid_generate_v4(), 'mer', 'Meru (mer)'),
(uuid_generate_v4(), 'mer-KE', 'Meru (Kenya) (mer-KE)'),
(uuid_generate_v4(), 'mn', 'Mongolian (mn)'),
(uuid_generate_v4(), 'mfe', 'Morisyen (mfe)'),
(uuid_generate_v4(), 'mfe-MU', 'Morisyen (Mauritius) (mfe-MU)'),
(uuid_generate_v4(), 'mua', 'Mundang (mua)'),
(uuid_generate_v4(), 'mua-CM', 'Mundang (Cameroon) (mua-CM)'),
(uuid_generate_v4(), 'naq', 'Nama (naq)'),
(uuid_generate_v4(), 'naq-NA', 'Nama (Namibia) (naq-NA)'),
(uuid_generate_v4(), 'ne', 'Nepali (ne)'),
(uuid_generate_v4(), 'ne-IN', 'Nepali (India) (ne-IN)'),
(uuid_generate_v4(), 'ne-NP', 'Nepali (Nepal) (ne-NP)'),
(uuid_generate_v4(), 'se', 'Northern Sami'),
(uuid_generate_v4(), 'se-FI', 'Northern Sami (Finland)'),
(uuid_generate_v4(), 'se-NO', 'Northern Sami (Norway)'),
(uuid_generate_v4(), 'se-SE', 'Northern Sami (Sweden)'),
(uuid_generate_v4(), 'nd', 'North Ndebele (nd)'),
(uuid_generate_v4(), 'nd-ZW', 'North Ndebele (Zimbabwe) (nd-ZW)'),
(uuid_generate_v4(), 'nb', 'Norwegian Bokmål (nb)'),
(uuid_generate_v4(), 'nb-NO', 'Norwegian Bokmål (Norway) (nb-NO)'),
(uuid_generate_v4(), 'nn', 'Norwegian Nynorsk (nn)'),
(uuid_generate_v4(), 'nn-NO', 'Norwegian Nynorsk (Norway) (nn-NO)'),
(uuid_generate_v4(), 'nus', 'Nuer (nus)'),
(uuid_generate_v4(), 'nus-SD', 'Nuer (Sudan) (nus-SD)'),
(uuid_generate_v4(), 'nyn', 'Nyankole (nyn)'),
(uuid_generate_v4(), 'nyn-UG', 'Nyankole (Uganda) (nyn-UG)'),
(uuid_generate_v4(), 'or', 'Oriya (or)'),
(uuid_generate_v4(), 'or-IN', 'Oriya (India) (or-IN)'),
(uuid_generate_v4(), 'om', 'Oromo (om)'),
(uuid_generate_v4(), 'om-ET', 'Oromo (Ethiopia) (om-ET)'),
(uuid_generate_v4(), 'om-KE', 'Oromo (Kenya) (om-KE)'),
(uuid_generate_v4(), 'ps', 'Pashto (ps)'),
(uuid_generate_v4(), 'ps-AF', 'Pashto (Afghanistan) (ps-AF)'),
(uuid_generate_v4(), 'fa', 'Persian (fa)'),
(uuid_generate_v4(), 'fa-AF', 'Persian (Afghanistan) (fa-AF)'),
(uuid_generate_v4(), 'fa-IR', 'Persian (Iran) (fa-IR)'),
(uuid_generate_v4(), 'pl', 'Polish (pl)'),
(uuid_generate_v4(), 'pl-PL', 'Polish (Poland) (pl-PL)'),
(uuid_generate_v4(), 'pt', 'Portuguese (pt)'),
(uuid_generate_v4(), 'pt-AO', 'Portuguese (Angola) (pt-AO)'),
(uuid_generate_v4(), 'pt-BR', 'Portuguese (Brazil) (pt-BR)'),
(uuid_generate_v4(), 'pt-GW', 'Portuguese (Guinea-Bissau) (pt-GW)'),
(uuid_generate_v4(), 'pt-MZ', 'Portuguese (Mozambique) (pt-MZ)'),
(uuid_generate_v4(), 'pt-PT', 'Portuguese (Portugal) (pt-PT)'),
(uuid_generate_v4(), 'pt-ST', 'Portuguese (São Tomé and Príncipe) (pt-ST)'),
(uuid_generate_v4(), 'pa', 'Punjabi (pa)'),
(uuid_generate_v4(), 'pa-Arab', 'Punjabi (Arabic) (pa-Arab)'),
(uuid_generate_v4(), 'pa-Arab-PK', 'Punjabi (Arabic, Pakistan) (pa-Arab-PK)'),
(uuid_generate_v4(), 'pa-Guru', 'Punjabi (Gurmukhi) (pa-Guru)'),
(uuid_generate_v4(), 'pa-Guru-IN', 'Punjabi (Gurmukhi, India) (pa-Guru-IN)'),
(uuid_generate_v4(), 'ro', 'Romanian (ro)'),
(uuid_generate_v4(), 'ro-MD', 'Romanian (Moldova) (ro-MD)'),
(uuid_generate_v4(), 'ro-RO', 'Romanian (Romania) (ro-RO)'),
(uuid_generate_v4(), 'rm', 'Romansh (rm)'),
(uuid_generate_v4(), 'rm-CH', 'Romansh (Switzerland) (rm-CH)'),
(uuid_generate_v4(), 'rof', 'Rombo (rof)'),
(uuid_generate_v4(), 'rof-TZ', 'Rombo (Tanzania) (rof-TZ)'),
(uuid_generate_v4(), 'rn', 'Rundi (rn)'),
(uuid_generate_v4(), 'rn-BI', 'Rundi (Burundi) (rn-BI)'),
(uuid_generate_v4(), 'ru', 'Russian (ru)'),
(uuid_generate_v4(), 'ru-MD', 'Russian (Moldova) (ru-MD)'),
(uuid_generate_v4(), 'ru-RU', 'Russian (Russia) (ru-RU)'),
(uuid_generate_v4(), 'ru-UA', 'Russian (Ukraine) (ru-UA)'),
(uuid_generate_v4(), 'rwk', 'Rwa (rwk)'),
(uuid_generate_v4(), 'rwk-TZ', 'Rwa (Tanzania) (rwk-TZ)'),
(uuid_generate_v4(), 'saq', 'Samburu (saq)'),
(uuid_generate_v4(), 'saq-KE', 'Samburu (Kenya) (saq-KE)'),
(uuid_generate_v4(), 'sg', 'Sango (sg)'),
(uuid_generate_v4(), 'sg-CF', 'Sango (Central African Republic) (sg-CF)'),
(uuid_generate_v4(), 'sbp', 'Sangu (sbp)'),
(uuid_generate_v4(), 'sbp-TZ', 'Sangu (Tanzania) (sbp-TZ)'),
(uuid_generate_v4(), 'sa', 'Sanskrit (sa)'),
(uuid_generate_v4(), 'gd', 'Scottish Gaelic (gd)'),
(uuid_generate_v4(), 'gd-GB', 'Scottish Gaelic (United Kingdom)'),
(uuid_generate_v4(), 'seh', 'Sena (seh)'),
(uuid_generate_v4(), 'seh-MZ', 'Sena (Mozambique) (seh-MZ)'),
(uuid_generate_v4(), 'sr', 'Serbian (sr)'),
(uuid_generate_v4(), 'sr-Cyrl', 'Serbian (Cyrillic) (sr-Cyrl)'),
(uuid_generate_v4(), 'sr-Cyrl-BA', 'Serbian (Cyrillic, Bosnia and Herzegovina)(sr-Cyrl-BA) '),
(uuid_generate_v4(), 'sr-Cyrl-ME', 'Serbian (Cyrillic, Montenegro) (sr-Cyrl-ME)'),
(uuid_generate_v4(), 'sr-Cyrl-RS', 'Serbian (Cyrillic, Serbia) (sr-Cyrl-RS)'),
(uuid_generate_v4(), 'sr-Latn', 'Serbian (Latin) (sr-Latn)'),
(uuid_generate_v4(), 'sr-Latn-BA', 'Serbian (Latin, Bosnia and Herzegovina) (sr-Latn-BA) '),
(uuid_generate_v4(), 'sr-Latn-ME', 'Serbian (Latin, Montenegro) (sr-Latn-ME)'),
(uuid_generate_v4(), 'sr-Latn-RS', 'Serbian (Latin, Serbia) (sr-Latn-RS)'),
(uuid_generate_v4(), 'ksb', 'Shambala (ksb)'),
(uuid_generate_v4(), 'ksb-TZ', 'Shambala (Tanzania) (ksb-TZ)'),
(uuid_generate_v4(), 'sn', 'Shona (sn)'),
(uuid_generate_v4(), 'sn-ZW', 'Shona (Zimbabwe) (sn-ZW)'),
(uuid_generate_v4(), 'ii', 'Sichuan Yi (ii)'),
(uuid_generate_v4(), 'ii-CN', 'Sichuan Yi (China) (ii-CN)'),
(uuid_generate_v4(), 'si', 'Sinhala (si)'),
(uuid_generate_v4(), 'si-LK', 'Sinhala (Sri Lanka) (si-LK)'),
(uuid_generate_v4(), 'sk', 'Slovak (sk)'),
(uuid_generate_v4(), 'sk-SK', 'Slovak (Slovakia) (sk-SK)'),
(uuid_generate_v4(), 'sl', 'Slovenian (sl)'),
(uuid_generate_v4(), 'sl-SI', 'Slovenian (Slovenia) (sl-SI)'),
(uuid_generate_v4(), 'xog', 'Soga (xog)'),
(uuid_generate_v4(), 'xog-UG', 'Soga (Uganda) (xog-UG)'),
(uuid_generate_v4(), 'so', 'Somali (so)'),
(uuid_generate_v4(), 'so-DJ', 'Somali (Djibouti) (so-DJ)'),
(uuid_generate_v4(), 'so-ET', 'Somali (Ethiopia) (so-ET)'),
(uuid_generate_v4(), 'so-KE', 'Somali (Kenya) (so-KE)'),
(uuid_generate_v4(), 'so-SO', 'Somali (Somalia) (so-SO)'),
(uuid_generate_v4(), 'es', 'Spanish (es)'),
(uuid_generate_v4(), 'es-AR', 'Spanish (Argentina) (es-AR)'),
(uuid_generate_v4(), 'es-BO', 'Spanish (Bolivia) (es-BO)'),
(uuid_generate_v4(), 'es-CL', 'Spanish (Chile) (es-CL)'),
(uuid_generate_v4(), 'es-CO', 'Spanish (Colombia) (es-CO)'),
(uuid_generate_v4(), 'es-CR', 'Spanish (Costa Rica) (es-CR)'),
(uuid_generate_v4(), 'es-DO', 'Spanish (Dominican Republic) (es-DO)'),
(uuid_generate_v4(), 'es-EC', 'Spanish (Ecuador) (es-EC)'),
(uuid_generate_v4(), 'es-SV', 'Spanish (El Salvador) (es-SV)'),
(uuid_generate_v4(), 'es-GQ', 'Spanish (Equatorial Guinea) (es-GQ)'),
(uuid_generate_v4(), 'es-GT', 'Spanish (Guatemala) (es-GT)'),
(uuid_generate_v4(), 'es-HN', 'Spanish (Honduras) (es-HN)'),
(uuid_generate_v4(), 'es-419', 'Spanish (Latin America) (es-419)'),
(uuid_generate_v4(), 'es-MX', 'Spanish (Mexico) (es-MX)'),
(uuid_generate_v4(), 'es-NI', 'Spanish (Nicaragua) (es-NI)'),
(uuid_generate_v4(), 'es-PA', 'Spanish (Panama) (es-PA)'),
(uuid_generate_v4(), 'es-PY', 'Spanish (Paraguay) (es-PY)'),
(uuid_generate_v4(), 'es-PE', 'Spanish (Peru) (es-PE)'),
(uuid_generate_v4(), 'es-PR', 'Spanish (Puerto Rico) (es-PR)'),
(uuid_generate_v4(), 'es-ES', 'Spanish (Spain) (es-ES)'),
(uuid_generate_v4(), 'es-US', 'Spanish (United States) (es-US)'),
(uuid_generate_v4(), 'es-UY', 'Spanish (Uruguay) (es-UY)'),
(uuid_generate_v4(), 'es-VE', 'Spanish (Venezuela) (es-VE)'),
(uuid_generate_v4(), 'sw', 'Swahili (sw)'),
(uuid_generate_v4(), 'sw-KE', 'Swahili (Kenya) (sw-KE)'),
(uuid_generate_v4(), 'sw-TZ', 'Swahili (Tanzania) (sw-TZ)'),
(uuid_generate_v4(), 'sv', 'Swedish (sv)'),
(uuid_generate_v4(), 'sv-FI', 'Swedish (Finland) (sv-FI)'),
(uuid_generate_v4(), 'sv-SE', 'Swedish (Sweden) (sv-SE)'),
(uuid_generate_v4(), 'gsw', 'Swiss German (gsw)'),
(uuid_generate_v4(), 'gsw-CH', 'Swiss German (Switzerland) (gsw-CH)'),
(uuid_generate_v4(), 'shi', 'Tachelhit (shi)'),
(uuid_generate_v4(), 'shi-Latn', 'Tachelhit (Latin) (shi-Latn)'),
(uuid_generate_v4(), 'shi-Latn-MA', 'Tachelhit (Latin, Morocco) (shi-Latn-MA)'),
(uuid_generate_v4(), 'shi-Tfng', 'Tachelhit (Tifinagh) (shi-Tfng)'),
(uuid_generate_v4(), 'shi-Tfng-MA', 'Tachelhit (Tifinagh, Morocco) (shi-Tfng-MA)'),
(uuid_generate_v4(), 'dav', 'Taita (dav)'),
(uuid_generate_v4(), 'dav-KE', 'Taita (Kenya) (dav-KE)'),
(uuid_generate_v4(), 'tg', 'Tajik (tg)'),
(uuid_generate_v4(), 'ta', 'Tamil (ta)'),
(uuid_generate_v4(), 'ta-IN', 'Tamil (India) (ta-IN)'),
(uuid_generate_v4(), 'ta-LK', 'Tamil (Sri Lanka) (ta-LK)'),
(uuid_generate_v4(), 'twq', 'Tasawaq (twq)'),
(uuid_generate_v4(), 'twq-NE', 'Tasawaq (Niger) (twq-NE)'),
(uuid_generate_v4(), 'mi', 'Te Reo Māori (mi)'),
(uuid_generate_v4(), 'te', 'Telugu (te)'),
(uuid_generate_v4(), 'te-IN', 'Telugu (India) (te-IN)'),
(uuid_generate_v4(), 'teo', 'Teso (teo)'),
(uuid_generate_v4(), 'teo-KE', 'Teso (Kenya) (teo-KE)'),
(uuid_generate_v4(), 'teo-UG', 'Teso (Uganda) (teo-UG)'),
(uuid_generate_v4(), 'th', 'Thai (th)'),
(uuid_generate_v4(), 'th-TH', 'Thai (Thailand) (th-TH)'),
(uuid_generate_v4(), 'bo', 'Tibetan (bo)'),
(uuid_generate_v4(), 'bo-CN', 'Tibetan (China) (bo-CN)'),
(uuid_generate_v4(), 'bo-IN', 'Tibetan (India) (bo-IN)'),
(uuid_generate_v4(), 'ti', 'Tigrinya (ti)'),
(uuid_generate_v4(), 'ti-ER', 'Tigrinya (Eritrea) (ti-ER)'),
(uuid_generate_v4(), 'ti-ET', 'Tigrinya (Ethiopia) (ti-ET)'),
(uuid_generate_v4(), 'to', 'Tongan (to)'),
(uuid_generate_v4(), 'to-TO', 'Tongan (Tonga) (to-TO)'),
(uuid_generate_v4(), 'tr', 'Turkish (tr)'),
(uuid_generate_v4(), 'tk', 'Turkmen (tk)'),
(uuid_generate_v4(), 'tr-TR', 'Turkish (Turkey) (tr-TR)'),
(uuid_generate_v4(), 'tch', 'Turks And Caicos Creole English'),
(uuid_generate_v4(), 'uk', 'Ukrainian (uk)'),
(uuid_generate_v4(), 'uk-UA', 'Ukrainian (Ukraine) (uk-UA)'),
(uuid_generate_v4(), 'ur', 'Urdu (ur)'),
(uuid_generate_v4(), 'ur-IN', 'Urdu (India) (ur-IN)'),
(uuid_generate_v4(), 'ur-PK', 'Urdu (Pakistan) (ur-PK)'),
(uuid_generate_v4(), 'ug', 'Uyghur'),
(uuid_generate_v4(), 'ug-CN', 'Uyghur (China)'),
(uuid_generate_v4(), 'uz', 'Uzbek (uz)'),
(uuid_generate_v4(), 'uz-Arab', 'Uzbek (Arabic) (uz-Arab)'),
(uuid_generate_v4(), 'uz-Arab-AF', 'Uzbek (Arabic, Afghanistan) (uz-Arab-AF)'),
(uuid_generate_v4(), 'uz-Cyrl', 'Uzbek (Cyrillic) (uz-Cyrl)'),
(uuid_generate_v4(), 'uz-Cyrl-UZ', 'Uzbek (Cyrillic, Uzbekistan) (uz-Cyrl-UZ)'),
(uuid_generate_v4(), 'uz-Latn', 'Uzbek (Latin) (uz-Latn)'),
(uuid_generate_v4(), 'uz-Latn-UZ', 'Uzbek (Latin, Uzbekistan) (uz-Latn-UZ)'),
(uuid_generate_v4(), 'vai', 'Vai (vai)'),
(uuid_generate_v4(), 'vai-Latn', 'Vai (Latin) (vai-Latn)'),
(uuid_generate_v4(), 'vai-Latn-LR', 'Vai (Latin, Liberia) (vai-Latn-LR)'),
(uuid_generate_v4(), 'vai-Vaii', 'Vai (Vai) (vai-Vaii)'),
(uuid_generate_v4(), 'vai-Vaii-LR', 'Vai (Vai, Liberia) (vai-Vaii-LR)'),
(uuid_generate_v4(), 'val', 'Valencian (val)'),
(uuid_generate_v4(), 'val-ES', 'Valencian (Spain) (val-ES)'),
(uuid_generate_v4(), 'ca-ES-valencia', 'Valencian (Spain Catalan) (ca-ES-valencia)'),
(uuid_generate_v4(), 'vi', 'Vietnamese (vi)'),
(uuid_generate_v4(), 'vi-VN', 'Vietnamese (Vietnam) (vi-VN)'),
(uuid_generate_v4(), 'vun', 'Vunjo (vun)'),
(uuid_generate_v4(), 'vun-TZ', 'Vunjo (Tanzania) (vun-TZ)'),
(uuid_generate_v4(), 'cy', 'Welsh (cy)'),
(uuid_generate_v4(), 'cy-GB', 'Welsh (United Kingdom) (cy-GB)'),
(uuid_generate_v4(), 'wo', 'Wolof (wo)'),
(uuid_generate_v4(), 'xh', 'Xhosa (xh)'),
(uuid_generate_v4(), 'yav', 'Yangben (yav)'),
(uuid_generate_v4(), 'yav-CM', 'Yangben (Cameroon) (yav-CM)'),
(uuid_generate_v4(), 'yo', 'Yoruba (yo)'),
(uuid_generate_v4(), 'yo-NG', 'Yoruba (Nigeria) (yo-NG)'),
(uuid_generate_v4(), 'dje', 'Zarma (dje)'),
(uuid_generate_v4(), 'dje-NE', 'Zarma (Niger) (dje-NE)'),
(uuid_generate_v4(), 'zu', 'Zulu (zu)'),
(uuid_generate_v4(), 'zu-ZA', 'Zulu (South Africa) (zu-ZA)');

-- Create the title table
CREATE TABLE
    title (
        title id UUID PRIMARY KEY DEFAULT uuid_generate_v4 (),
        work_id UUID NOT NULL REFERENCES work (work_id) ON DELETE CASCADE,
        locale_id UUID NOT NULL REFERENCES locale (locale_id) ON DELETE CASCADE,
        full_title TEXT NOT NULL CHECK (octet_length(full_title) >= 1),
        title TEXT NOT NULL CHECK (octet_length(title) >= 1),
        subtitle TEXT CHECK (octet_length(subtitle) >= 1),
    );

-- Migrate existing work titles to the title table with English locale
INSERT INTO
    title (
        id,
        work_id,
        locale_id,
        full_title,
        title,
        subtitle
    )
SELECT
    UUID (),
    work_id,
    (
        SELECT
            locale_id
        FROM
            locale
        WHERE
            code = 'en'
        LIMIT
            1
    ),
    full_title,
    title,
    subtitle
FROM
    work
WHERE
    full_title IS NOT NULL
    AND title IS NOT NULL;

-- Drop title-related columns from the work table
ALTER TABLE work
DROP COLUMN full_title,
DROP COLUMN title,
DROP COLUMN subtitle;