//! Managed-DRIVER Metrics ingestion lifecycle (`MET-WP2-02`).
//!
//! This module owns the repository-internal protocol behind the five protected
//! `METRICS_INGEST_SERVICE` lifecycle operations. It is transport and lifecycle
//! only: canonical ingestion is delegated unchanged to
//! [`ingest_metric_batch`](crate::model::metric_ingestion::ingest_metric_batch),
//! and the only durable state touched here is the existing
//! `metric_source_checkpoint` lease/progress row, the existing `metric_import`
//! envelope and, read-only, the committed `metric_import_batch` and
//! `metric_coverage` evidence. There is no second queue, no process-local claim
//! ledger and no generic worker or job abstraction.
//!
//! # One source unit
//!
//! For MOM-1 a source unit is one source account's single `default` checkpoint
//! partition. The lifecycle of one collected day is:
//!
//! ```text
//! claim_metric_source_units       lazily create, then lease (source_account_id, "default")
//!   -> begin_metric_import        create or recover the one import for the upstream report
//!   -> ingest_metric_batch_under_claim   every expected batch, through the #900 coordinator
//!   -> complete_metric_import     close the import from its committed batches
//!   -> update_metric_source_checkpoint   record progress and release the lease
//! ```
//!
//! # Claim token
//!
//! `metric_source_checkpoint.lease_owner` holds the canonical lowercase text of
//! an opaque UUID generated by Thoth for every successful claim or reclaim. It
//! is returned only in the fresh claim, is never a principal identity, and is
//! required by every later operation. A caller holds a *live* claim only while
//! the stored token equals its token and `lease_expires_at` is after the
//! transaction timestamp, both checked under the checkpoint row lock.
//!
//! # Transactions and lock order
//!
//! Every operation except the batch runs in one transaction that, after the
//! caller's authorization, locks the account's `default` checkpoint row
//! `FOR UPDATE` before reading or writing anything else it depends on. Source
//! authority rows are then read `FOR SHARE` in the canonical coordinator's own
//! order (account, source, platform, publisher). Because every lease-sensitive
//! operation on one account queues on that one row first, begin, batch,
//! completion and checkpoint progress for one account are serialized.
//!
//! The batch uses the bounded two-connection guard fixed by Specification
//! Amendment 2: a short guard transaction locks and validates the checkpoint
//! row, checks the batch key, and **while holding that lock** calls the
//! unchanged coordinator, which uses its own pooled connection and transaction.
//! A concurrent reclaim uses `FOR UPDATE SKIP LOCKED` on the same row, so it
//! cannot replace the token while the coordinator runs. Nothing outside the
//! local coordinator call happens inside the guard.

use std::collections::BTreeSet;

use chrono::NaiveDate;
use diesel::pg::PgConnection;
use diesel::r2d2::PoolError;
use diesel::result::Error as DieselError;
use diesel::sql_types::{
    Array, BigInt, Bool, Date as SqlDate, Integer, Nullable, Text, Timestamptz, Uuid as SqlUuid,
};
use diesel::{sql_query, Connection, ExpressionMethods, OptionalExtension, QueryDsl, RunQueryDsl};
use juniper::{FieldError, IntoFieldError};
use serde_json::{json, Value as JsonValue};
use uuid::Uuid;

use crate::db::PgPool;
use crate::model::metric_coverage::MetricCoverageStatus;
use crate::model::metric_import::{MetricImport, MetricImportStatus};
use crate::model::metric_ingestion::{
    ingest_metric_batch, MetricIngestionBatch, MetricIngestionErrorCode, MetricIngestionOutcome,
    NormalizedMetricCoverageAssertion, NormalizedMetricObservation, MAX_BATCH_KEY_BYTES,
};
use crate::model::metric_platform::MetricPlatform;
use crate::model::metric_platform_measure::MetricReportingGrain;
use crate::model::metric_record_provenance::MetricRecordProvenanceClassification;
use crate::model::metric_source::{MetricSource, MetricSourceAcquisitionType};
use crate::model::metric_source_account::{check_source_compatibility, MetricSourceAccount};
use crate::model::metric_source_checkpoint::MetricSourceCheckpoint;
use crate::model::publication::PublicationType;
use crate::model::publisher::{PublisherCapability, ThothPackage};
use crate::model::Timestamp;
use crate::schema::{
    metric_import, metric_import_batch, metric_platform, metric_source, metric_source_account,
    metric_source_checkpoint, publisher,
};

#[cfg(test)]
pub(crate) mod tests;

/// The only MOM-1 checkpoint partition. It is fixed by Thoth, never supplied.
pub const DEFAULT_PARTITION_KEY: &str = "default";
/// Claim limit used when the caller does not supply one.
pub const CLAIM_DEFAULT_LIMIT: i32 = 10;
/// Largest number of source units one claim returns; larger limits are clamped.
pub const CLAIM_MAX_LIMIT: i32 = 50;
/// Lease duration used when the caller does not supply one.
pub const LEASE_DEFAULT_SECONDS: i32 = 900;
/// Shortest lease a claim grants; shorter requests are clamped up.
pub const LEASE_MIN_SECONDS: i32 = 60;
/// Longest lease a claim grants; longer requests are clamped down.
pub const LEASE_MAX_SECONDS: i32 = 3600;
/// Maximum `upstreamReportId` length in UTF-8 bytes.
pub const MAX_UPSTREAM_REPORT_ID_BYTES: usize = 512;
/// Maximum `formatCode`, `formatVersion` and `normalizerVersion` length in
/// UTF-8 bytes.
pub const MAX_FORMAT_FIELD_BYTES: usize = 128;
/// Maximum number of expected batch keys one import may declare.
pub const MAX_EXPECTED_BATCH_KEYS: usize = 100;
/// The fixed schema of the server-owned manifest envelope a managed-DRIVER
/// import stores.
pub const MANAGED_IMPORT_MANIFEST_SCHEMA: &str = "thoth-managed-driver-import/1";

// --------------------------------------------------------------------------
// Errors
// --------------------------------------------------------------------------

/// A lifecycle failure: one of the closed lifecycle classifications frozen by
/// Specification Amendment 3, or an authoritative coordinator code carried
/// through without rewriting.
///
/// Every failure rolls back its transaction, so a failed call leaves durable
/// state exactly as it was. No variant carries SQL, a constraint name, a
/// connection detail, a token, configuration or caller input.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MetricLifecycleError {
    /// No source carries the requested stable code.
    SourceNotFound,
    /// No source account carries the requested stable code.
    SourceAccountNotFound,
    /// The source or account is not an enabled, correctly configured managed
    /// `DRIVER` route with an enabled platform and a pinned publisher.
    SourceNotEligible,
    /// The account's pinned publisher lacks the `METRICS_COLLECT` capability.
    MetricsCollectNotEntitled,
    /// The caller does not hold the live claim: the token is unknown, foreign,
    /// expired, reclaimed or already released.
    StaleSourceClaim,
    /// No import carries the requested identifier.
    ImportNotFound,
    /// An import already exists for the upstream report with different
    /// immutable values.
    ImportIdempotencyMismatch,
    /// The batch key is not one the import declared.
    UnexpectedBatchKey,
    /// Not every expected batch has been committed.
    ImportIncomplete,
    /// The import is not a managed-DRIVER import in a state the operation
    /// accepts.
    InvalidImportState,
    /// A lifecycle input is outside its approved bounds or format.
    LifecycleLimitExceeded,
    /// A failure owned by the canonical ingestion coordinator vocabulary.
    Ingestion(MetricIngestionErrorCode),
}

impl MetricLifecycleError {
    /// The stable machine-readable code, returned as `extensions.type`.
    pub fn code(self) -> String {
        use MetricLifecycleError::*;
        match self {
            SourceNotFound => "SOURCE_NOT_FOUND".to_string(),
            SourceAccountNotFound => "SOURCE_ACCOUNT_NOT_FOUND".to_string(),
            SourceNotEligible => "SOURCE_NOT_ELIGIBLE".to_string(),
            MetricsCollectNotEntitled => "METRICS_COLLECT_NOT_ENTITLED".to_string(),
            StaleSourceClaim => "STALE_SOURCE_CLAIM".to_string(),
            ImportNotFound => "IMPORT_NOT_FOUND".to_string(),
            ImportIdempotencyMismatch => "IMPORT_IDEMPOTENCY_MISMATCH".to_string(),
            UnexpectedBatchKey => "UNEXPECTED_BATCH_KEY".to_string(),
            ImportIncomplete => "IMPORT_INCOMPLETE".to_string(),
            InvalidImportState => "INVALID_IMPORT_STATE".to_string(),
            LifecycleLimitExceeded => "LIFECYCLE_LIMIT_EXCEEDED".to_string(),
            Ingestion(code) => code.to_string(),
        }
    }

    /// The fixed client-facing message. Never derived from input or state.
    pub fn message(self) -> &'static str {
        use MetricLifecycleError::*;
        match self {
            SourceNotFound => "The metric source was not found.",
            SourceAccountNotFound => "The metric source account was not found.",
            SourceNotEligible => "The metric source is not eligible for managed collection.",
            MetricsCollectNotEntitled => {
                "The publisher is not entitled to managed metrics collection."
            }
            StaleSourceClaim => "The source claim is not held by this lease token.",
            ImportNotFound => "The metric import was not found.",
            ImportIdempotencyMismatch => {
                "A metric import already exists for this upstream report with different values."
            }
            UnexpectedBatchKey => "The batch key is not one the metric import expects.",
            ImportIncomplete => "Not every expected batch of the metric import has been ingested.",
            InvalidImportState => "The metric import is not in a state this operation accepts.",
            LifecycleLimitExceeded => "A lifecycle input is outside its permitted bounds.",
            Ingestion(_) => "The metric ingestion request was refused.",
        }
    }
}

impl std::fmt::Display for MetricLifecycleError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.code())
    }
}

impl std::error::Error for MetricLifecycleError {}

impl From<MetricIngestionErrorCode> for MetricLifecycleError {
    fn from(code: MetricIngestionErrorCode) -> Self {
        MetricLifecycleError::Ingestion(code)
    }
}

impl From<DieselError> for MetricLifecycleError {
    fn from(error: DieselError) -> Self {
        log::error!("metric ingestion lifecycle database failure: {error}");
        MetricLifecycleError::Ingestion(MetricIngestionErrorCode::InternalDatabaseError)
    }
}

impl From<PoolError> for MetricLifecycleError {
    fn from(error: PoolError) -> Self {
        log::error!("metric ingestion lifecycle could not obtain a database connection: {error}");
        MetricLifecycleError::Ingestion(MetricIngestionErrorCode::InternalDatabaseError)
    }
}

impl IntoFieldError for MetricLifecycleError {
    fn into_field_error(self) -> FieldError {
        let mut extensions = juniper::Object::with_capacity(1);
        extensions.add_field("type", juniper::Value::scalar(self.code()));
        FieldError::new(self.message(), juniper::Value::Object(extensions))
    }
}

type LifecycleResult<T> = Result<T, MetricLifecycleError>;

// --------------------------------------------------------------------------
// Transport inputs and outputs
// --------------------------------------------------------------------------

/// Which source to claim units of, how many, and for how long.
#[derive(juniper::GraphQLInputObject, Debug, Clone, PartialEq, Eq)]
#[graphql(description = "Which managed DRIVER source to claim units of, how many and for how long")]
pub struct ClaimMetricSourceUnitsInput {
    #[graphql(description = "Exact stable code of the source. It is never normalised")]
    pub source_code: String,
    #[graphql(
        default = 10,
        description = "Maximum units to claim. Values above 50 are clamped to 50; values at or below 0 claim nothing"
    )]
    pub limit: Option<i32>,
    #[graphql(
        default = 900,
        description = "Requested lease duration in seconds, clamped to the range 60 to 3600"
    )]
    pub lease_seconds: Option<i32>,
}

/// The managed-DRIVER import envelope for one collected unit.
#[derive(juniper::GraphQLInputObject, Debug, Clone, PartialEq, Eq)]
#[graphql(
    description = "The import envelope for one collected unit of a claimed managed DRIVER source account"
)]
pub struct BeginMetricImportInput {
    #[graphql(description = "Exact stable code of the claimed source account")]
    pub source_account_code: String,
    #[graphql(description = "The lease token returned by the claim")]
    pub lease_token: Uuid,
    #[graphql(
        description = "Deterministic upstream report identity, unique within the source account. Non-blank, at most 512 UTF-8 bytes"
    )]
    pub upstream_report_id: String,
    #[graphql(description = "First day of the collected unit")]
    pub period_start: NaiveDate,
    #[graphql(
        description = "Exclusive end of the collected unit; exactly one day after periodStart"
    )]
    pub period_end: NaiveDate,
    #[graphql(description = "Source format code. Non-blank, at most 128 UTF-8 bytes")]
    pub format_code: String,
    #[graphql(description = "Source format version. Non-blank, at most 128 UTF-8 bytes")]
    pub format_version: String,
    #[graphql(description = "Normalizer version. Non-blank, at most 128 UTF-8 bytes")]
    pub normalizer_version: String,
    #[graphql(
        description = "SHA-256 of the raw source evidence, if known: 64 lowercase hexadecimal characters"
    )]
    pub raw_sha256: Option<String>,
    #[graphql(
        description = "SHA-256 of the deterministic source manifest for this unit: 64 lowercase hexadecimal characters"
    )]
    pub manifest_digest: String,
    #[graphql(
        description = "Every batch key that will be ingested for this import: 1 to 100 unique non-blank keys of at most 256 UTF-8 bytes"
    )]
    pub expected_batch_keys: Vec<String>,
}

/// One `thoth-normalized-metrics/1` observation, mapped one-to-one onto the
/// coordinator's observation.
#[derive(juniper::GraphQLInputObject, Debug, Clone, PartialEq, Eq)]
#[graphql(description = "One thoth-normalized-metrics/1 observation")]
pub struct NormalizedMetricObservationInput {
    #[graphql(description = "Exact stable code of the reporting source account")]
    pub source_account_code: String,
    #[graphql(description = "Exact stable code of the platform")]
    pub platform_code: String,
    #[graphql(description = "Exact stable code of the measure")]
    pub measure_code: String,
    #[graphql(description = "DOI of the work")]
    pub work_doi: String,
    #[graphql(description = "ISBN-13 of the publication, if the observation is publication-level")]
    pub publication_isbn: Option<String>,
    #[graphql(description = "Type of the publication, if the observation is publication-level")]
    pub publication_type: Option<PublicationType>,
    #[graphql(description = "Start of the half-open observation period")]
    pub period_start: NaiveDate,
    #[graphql(description = "Exclusive end of the observation period")]
    pub period_end: NaiveDate,
    #[graphql(description = "Reporting grain of the observation")]
    pub reporting_grain: MetricReportingGrain,
    #[graphql(description = "Uppercase ISO 3166-1 alpha-2 country code, if country-level")]
    pub country_code: Option<String>,
    #[graphql(description = "ROR of the institution, if institution-level")]
    pub institution_ror: Option<String>,
    #[graphql(description = "The value as a canonical base-10 signed 64-bit integer string")]
    pub value: String,
    #[graphql(description = "Source-side record identifier, if any")]
    pub source_record_id: Option<String>,
    #[graphql(description = "Methodology version of the value")]
    pub methodology_version: String,
    #[graphql(description = "Non-negative source row number, if any")]
    pub source_row_number: Option<i32>,
}

/// One explicit coverage assertion, mapped one-to-one onto the coordinator's
/// coverage assertion.
#[derive(juniper::GraphQLInputObject, Debug, Clone, PartialEq, Eq)]
#[graphql(description = "One explicit thoth-normalized-metrics/1 coverage assertion")]
pub struct NormalizedMetricCoverageAssertionInput {
    #[graphql(description = "Exact stable code of the platform")]
    pub platform_code: String,
    #[graphql(description = "Exact stable code of the measure")]
    pub measure_code: String,
    #[graphql(description = "Start of the half-open covered period")]
    pub period_start: NaiveDate,
    #[graphql(description = "Exclusive end of the covered period")]
    pub period_end: NaiveDate,
    #[graphql(description = "Whether the period is completely covered")]
    pub status: MetricCoverageStatus,
    #[graphql(description = "Whether the coverage includes the country dimension")]
    pub country_coverage: bool,
    #[graphql(description = "Whether the coverage includes the institution dimension")]
    pub institution_coverage: bool,
    #[graphql(description = "Optional note")]
    pub notes: Option<String>,
}

/// One bounded normalized batch for a claimed import.
#[derive(juniper::GraphQLInputObject, Debug, Clone, PartialEq, Eq)]
#[graphql(description = "One bounded thoth-normalized-metrics/1 batch for a claimed metric import")]
pub struct IngestMetricBatchInput {
    #[graphql(description = "Thoth ID of the import returned by beginMetricImport")]
    pub import_id: Uuid,
    #[graphql(description = "The lease token returned by the claim")]
    pub lease_token: Uuid,
    #[graphql(
        description = "One of the import's expected batch keys; also the batch idempotency key"
    )]
    pub batch_key: String,
    #[graphql(description = "Exactly thoth-normalized-metrics/1")]
    pub schema_version: String,
    #[graphql(description = "At most 500 observations, in batch row order")]
    pub observations: Vec<NormalizedMetricObservationInput>,
    #[graphql(description = "At most 100 explicit coverage assertions")]
    pub coverage: Vec<NormalizedMetricCoverageAssertionInput>,
}

/// Which claimed import to complete.
#[derive(juniper::GraphQLInputObject, Debug, Clone, PartialEq, Eq)]
#[graphql(description = "Which claimed metric import to complete")]
pub struct CompleteMetricImportInput {
    #[graphql(description = "Thoth ID of the import")]
    pub import_id: Uuid,
    #[graphql(description = "The lease token returned by the claim")]
    pub lease_token: Uuid,
}

/// Which terminal import's progress to record.
#[derive(juniper::GraphQLInputObject, Debug, Clone, PartialEq, Eq)]
#[graphql(
    description = "Which terminal metric import to record on its source account checkpoint, releasing the claim"
)]
pub struct UpdateMetricSourceCheckpointInput {
    #[graphql(description = "Thoth ID of the terminal import")]
    pub import_id: Uuid,
    #[graphql(description = "The lease token returned by the claim")]
    pub lease_token: Uuid,
}

/// One freshly claimed source unit.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MetricSourceUnitClaim {
    pub source: MetricSource,
    pub source_account: MetricSourceAccount,
    pub checkpoint: MetricSourceCheckpoint,
    pub lease_token: Uuid,
    pub lease_expires_at: Timestamp,
}

/// The committed or replayed outcome of one batch, as returned by the
/// coordinator.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MetricBatchResult {
    pub import_batch_id: Uuid,
    pub request_hash: String,
    pub replayed: bool,
    pub rows: Vec<MetricIngestionRowResult>,
}

/// One observation's durable classification.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MetricIngestionRowResult {
    pub batch_row_index: i32,
    pub classification: MetricRecordProvenanceClassification,
    pub reason_code: Option<MetricIngestionErrorCode>,
    pub record_id: Option<Uuid>,
    pub identity_hash: Option<String>,
    pub content_hash: Option<String>,
}

impl TryFrom<MetricIngestionOutcome> for MetricBatchResult {
    type Error = MetricLifecycleError;

    fn try_from(outcome: MetricIngestionOutcome) -> LifecycleResult<Self> {
        let rows = outcome
            .rows
            .into_iter()
            .map(|row| {
                Ok(MetricIngestionRowResult {
                    batch_row_index: i32::try_from(row.batch_row_index)
                        .map_err(|_| MetricIngestionErrorCode::InternalStateInconsistency)?,
                    classification: row.classification,
                    reason_code: row.reason_code,
                    record_id: row.record_id,
                    identity_hash: row.identity_hash,
                    content_hash: row.content_hash,
                })
            })
            .collect::<LifecycleResult<Vec<_>>>()?;
        Ok(MetricBatchResult {
            import_batch_id: outcome.import_batch_id,
            request_hash: outcome.request_hash,
            replayed: outcome.replayed,
            rows,
        })
    }
}

// --------------------------------------------------------------------------
// Shared checks
// --------------------------------------------------------------------------

fn is_blank(value: &str) -> bool {
    value.trim().is_empty()
}

fn is_lowercase_sha256_hex(value: &str) -> bool {
    value.len() == 64
        && value
            .bytes()
            .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
}

fn bounded_text(value: &str, max_bytes: usize) -> bool {
    !is_blank(value) && value.len() <= max_bytes
}

/// The server-owned manifest envelope. Keys are stored in ascending byte
/// order, so the envelope identifies the *set* of expected batches.
fn manifest_envelope(manifest_digest: &str, keys: &BTreeSet<String>) -> JsonValue {
    json!({
        "schemaVersion": MANAGED_IMPORT_MANIFEST_SCHEMA,
        "manifestDigest": manifest_digest,
        "expectedBatchKeys": keys.iter().collect::<Vec<_>>(),
    })
}

/// Decode a stored managed-DRIVER manifest envelope into its expected batch
/// keys. Anything that is not exactly that envelope fails closed.
pub(crate) fn expected_batch_keys(manifest: &JsonValue) -> Option<BTreeSet<String>> {
    let object = manifest.as_object()?;
    if object.len() != 3
        || object.get("schemaVersion")?.as_str()? != MANAGED_IMPORT_MANIFEST_SCHEMA
        || !is_lowercase_sha256_hex(object.get("manifestDigest")?.as_str()?)
    {
        return None;
    }
    let keys = object.get("expectedBatchKeys")?.as_array()?;
    let set: BTreeSet<String> = keys
        .iter()
        .map(|key| key.as_str().map(str::to_string))
        .collect::<Option<_>>()?;
    (!set.is_empty() && set.len() == keys.len()).then_some(set)
}

/// Validate the begin-import request without touching the database, returning
/// the expected batch-key set.
fn validate_begin(input: &BeginMetricImportInput) -> LifecycleResult<BTreeSet<String>> {
    let keys: BTreeSet<String> = input.expected_batch_keys.iter().cloned().collect();
    let valid = bounded_text(&input.upstream_report_id, MAX_UPSTREAM_REPORT_ID_BYTES)
        && input.period_start.succ_opt() == Some(input.period_end)
        && bounded_text(&input.format_code, MAX_FORMAT_FIELD_BYTES)
        && bounded_text(&input.format_version, MAX_FORMAT_FIELD_BYTES)
        && bounded_text(&input.normalizer_version, MAX_FORMAT_FIELD_BYTES)
        && input
            .raw_sha256
            .as_deref()
            .is_none_or(is_lowercase_sha256_hex)
        && is_lowercase_sha256_hex(&input.manifest_digest)
        && !keys.is_empty()
        && keys.len() <= MAX_EXPECTED_BATCH_KEYS
        && keys.len() == input.expected_batch_keys.len()
        && keys
            .iter()
            .all(|key| bounded_text(key, MAX_BATCH_KEY_BYTES));
    if valid {
        Ok(keys)
    } else {
        Err(MetricLifecycleError::LifecycleLimitExceeded)
    }
}

/// Parse a canonical base-10 signed 64-bit integer: no sign other than a
/// leading `-`, no leading zero, no `-0`, no whitespace, no exponent.
fn parse_canonical_i64(value: &str) -> Option<i64> {
    let parsed: i64 = value.parse().ok()?;
    (parsed.to_string() == value).then_some(parsed)
}

/// Map the transport batch onto the coordinator's request, converting only the
/// two representation-level fields and interpreting nothing else.
fn to_coordinator_batch(input: &IngestMetricBatchInput) -> LifecycleResult<MetricIngestionBatch> {
    let observations = input
        .observations
        .iter()
        .map(|observation| {
            let value = parse_canonical_i64(&observation.value)
                .ok_or(MetricLifecycleError::LifecycleLimitExceeded)?;
            let source_row_number = observation
                .source_row_number
                .map(|number| {
                    if number < 0 {
                        Err(MetricLifecycleError::LifecycleLimitExceeded)
                    } else {
                        Ok(i64::from(number))
                    }
                })
                .transpose()?;
            Ok(NormalizedMetricObservation {
                source_account_code: observation.source_account_code.clone(),
                platform_code: observation.platform_code.clone(),
                measure_code: observation.measure_code.clone(),
                work_doi: observation.work_doi.clone(),
                publication_isbn: observation.publication_isbn.clone(),
                publication_type: observation.publication_type,
                period_start: observation.period_start,
                period_end: observation.period_end,
                reporting_grain: observation.reporting_grain,
                country_code: observation.country_code.clone(),
                institution_ror: observation.institution_ror.clone(),
                value,
                source_record_id: observation.source_record_id.clone(),
                methodology_version: observation.methodology_version.clone(),
                source_row_number,
            })
        })
        .collect::<LifecycleResult<Vec<_>>>()?;
    let coverage = input
        .coverage
        .iter()
        .map(|assertion| NormalizedMetricCoverageAssertion {
            platform_code: assertion.platform_code.clone(),
            measure_code: assertion.measure_code.clone(),
            period_start: assertion.period_start,
            period_end: assertion.period_end,
            status: assertion.status,
            country_coverage: assertion.country_coverage,
            institution_coverage: assertion.institution_coverage,
            notes: assertion.notes.clone(),
        })
        .collect();
    Ok(MetricIngestionBatch {
        import_id: input.import_id,
        batch_key: input.batch_key.clone(),
        schema_version: input.schema_version.clone(),
        observations,
        coverage,
    })
}

/// Whether one source account is an eligible managed-DRIVER route for its
/// source, returning its pinned publisher.
///
/// `lock` reads the platform and publisher `FOR SHARE`, the order the
/// canonical coordinator uses; the claim path reads them without locks, since
/// every later operation revalidates under locks.
fn check_eligibility(
    connection: &mut PgConnection,
    source: &MetricSource,
    account: &MetricSourceAccount,
    lock: bool,
) -> LifecycleResult<Uuid> {
    use MetricLifecycleError::{MetricsCollectNotEntitled, SourceNotEligible};
    if source.acquisition_type != MetricSourceAcquisitionType::Driver
        || !source.enabled
        || !account.enabled
        || account.source_id != source.source_id
    {
        return Err(SourceNotEligible);
    }
    let platform_query = metric_platform::table.find(account.platform_id);
    let platform: Option<MetricPlatform> = if lock {
        platform_query.for_share().first(connection).optional()?
    } else {
        platform_query.first(connection).optional()?
    };
    if !platform.is_some_and(|platform| platform.enabled) {
        return Err(SourceNotEligible);
    }
    let publisher_id = account.expected_publisher_id.ok_or(SourceNotEligible)?;
    let package_query = publisher::table
        .find(publisher_id)
        .select(publisher::subscription_package);
    let package: Option<ThothPackage> = if lock {
        package_query.for_share().first(connection).optional()?
    } else {
        package_query.first(connection).optional()?
    };
    let package = package.ok_or(SourceNotEligible)?;
    let configuration = account
        .decoded_configuration()
        .map_err(|_| SourceNotEligible)?;
    check_source_compatibility(source, configuration.kind).map_err(|_| SourceNotEligible)?;
    if !package.has_capability(PublisherCapability::MetricsCollect) {
        return Err(MetricsCollectNotEntitled);
    }
    Ok(publisher_id)
}

/// The account's `default` checkpoint, locked `FOR UPDATE`, with its lease
/// liveness decided against the transaction timestamp.
#[derive(diesel::QueryableByName)]
struct LockedCheckpoint {
    #[diesel(sql_type = SqlUuid)]
    source_checkpoint_id: Uuid,
    #[diesel(sql_type = Nullable<Text>)]
    lease_owner: Option<String>,
    #[diesel(sql_type = Bool)]
    lease_is_live: bool,
}

fn lock_checkpoint(
    connection: &mut PgConnection,
    source_account_id: Uuid,
) -> LifecycleResult<Option<LockedCheckpoint>> {
    Ok(sql_query(
        "SELECT source_checkpoint_id, lease_owner, \
                (lease_expires_at IS NOT NULL \
                 AND lease_expires_at > transaction_timestamp()) AS lease_is_live \
           FROM metric_source_checkpoint \
          WHERE source_account_id = $1 AND partition_key = $2 \
          FOR UPDATE",
    )
    .bind::<SqlUuid, _>(source_account_id)
    .bind::<Text, _>(DEFAULT_PARTITION_KEY)
    .get_result(connection)
    .optional()?)
}

/// Whether the locked checkpoint is held by exactly this live token.
fn holds_live_claim(checkpoint: &LockedCheckpoint, lease_token: Uuid) -> bool {
    checkpoint.lease_is_live
        && checkpoint.lease_owner.as_deref() == Some(lease_token.to_string().as_str())
}

/// Lock the account's checkpoint and require the caller's live claim.
fn require_live_claim(
    connection: &mut PgConnection,
    source_account_id: Uuid,
    lease_token: Uuid,
) -> LifecycleResult<Uuid> {
    match lock_checkpoint(connection, source_account_id)? {
        Some(checkpoint) if holds_live_claim(&checkpoint, lease_token) => {
            Ok(checkpoint.source_checkpoint_id)
        }
        _ => Err(MetricLifecycleError::StaleSourceClaim),
    }
}

fn find_import(connection: &mut PgConnection, import_id: Uuid) -> LifecycleResult<MetricImport> {
    metric_import::table
        .find(import_id)
        .first(connection)
        .optional()?
        .ok_or(MetricLifecycleError::ImportNotFound)
}

// --------------------------------------------------------------------------
// Operations
// --------------------------------------------------------------------------

#[derive(diesel::QueryableByName)]
struct CheckpointId {
    #[diesel(sql_type = SqlUuid)]
    source_checkpoint_id: Uuid,
}

/// Claim up to `limit` units of one managed-DRIVER source.
///
/// One transaction: resolve the source, select the eligible enabled accounts in
/// ascending stable-code order, ensure each has its `default` checkpoint with a
/// conflict-safe insert, lock the unleased or expired checkpoints
/// `FOR UPDATE SKIP LOCKED` in the same order, and lease each under a fresh
/// token. A row another claimer holds locked is skipped, never waited on. An
/// ineligible account is skipped and gains no checkpoint.
pub fn claim_metric_source_units(
    db: &PgPool,
    input: &ClaimMetricSourceUnitsInput,
) -> LifecycleResult<Vec<MetricSourceUnitClaim>> {
    let limit = input.limit.unwrap_or(CLAIM_DEFAULT_LIMIT);
    if limit <= 0 {
        return Ok(Vec::new());
    }
    let limit = limit.min(CLAIM_MAX_LIMIT);
    let lease_seconds = input
        .lease_seconds
        .unwrap_or(LEASE_DEFAULT_SECONDS)
        .clamp(LEASE_MIN_SECONDS, LEASE_MAX_SECONDS);

    let mut connection = db.get()?;
    connection.transaction(|connection| {
        let source: MetricSource = metric_source::table
            .filter(metric_source::code.eq(&input.source_code))
            .first(connection)
            .optional()?
            .ok_or(MetricLifecycleError::SourceNotFound)?;
        if source.acquisition_type != MetricSourceAcquisitionType::Driver || !source.enabled {
            return Err(MetricLifecycleError::SourceNotEligible);
        }

        let accounts: Vec<MetricSourceAccount> = metric_source_account::table
            .filter(metric_source_account::source_id.eq(source.source_id))
            .filter(metric_source_account::enabled.eq(true))
            .order(metric_source_account::code.asc())
            .load(connection)?;
        let mut eligible = Vec::with_capacity(accounts.len());
        for account in accounts {
            match check_eligibility(connection, &source, &account, false) {
                Ok(_) => eligible.push(account),
                Err(
                    MetricLifecycleError::SourceNotEligible
                    | MetricLifecycleError::MetricsCollectNotEntitled,
                ) => {}
                Err(error) => return Err(error),
            }
        }
        if eligible.is_empty() {
            return Ok(Vec::new());
        }

        for account in &eligible {
            diesel::insert_into(metric_source_checkpoint::table)
                .values((
                    metric_source_checkpoint::source_account_id.eq(account.source_account_id),
                    metric_source_checkpoint::partition_key.eq(DEFAULT_PARTITION_KEY),
                ))
                .on_conflict((
                    metric_source_checkpoint::source_account_id,
                    metric_source_checkpoint::partition_key,
                ))
                .do_nothing()
                .execute(connection)?;
        }

        let account_ids: Vec<Uuid> = eligible.iter().map(|a| a.source_account_id).collect();
        let selected: Vec<CheckpointId> = sql_query(
            "SELECT c.source_checkpoint_id \
               FROM metric_source_checkpoint c \
               JOIN metric_source_account a ON a.source_account_id = c.source_account_id \
              WHERE c.source_account_id = ANY($1) \
                AND c.partition_key = $2 \
                AND (c.lease_expires_at IS NULL \
                     OR c.lease_expires_at <= transaction_timestamp()) \
              ORDER BY a.code \
              LIMIT $3 \
              FOR UPDATE OF c SKIP LOCKED",
        )
        .bind::<Array<SqlUuid>, _>(&account_ids)
        .bind::<Text, _>(DEFAULT_PARTITION_KEY)
        .bind::<BigInt, _>(i64::from(limit))
        .load(connection)?;

        let mut claims = Vec::with_capacity(selected.len());
        for row in selected {
            let lease_token = Uuid::new_v4();
            sql_query(
                "UPDATE metric_source_checkpoint \
                    SET lease_owner = $1, \
                        lease_expires_at = transaction_timestamp() + ($2 * interval '1 second') \
                  WHERE source_checkpoint_id = $3",
            )
            .bind::<Text, _>(lease_token.to_string())
            .bind::<Integer, _>(lease_seconds)
            .bind::<SqlUuid, _>(row.source_checkpoint_id)
            .execute(connection)?;
            let checkpoint: MetricSourceCheckpoint = metric_source_checkpoint::table
                .find(row.source_checkpoint_id)
                .first(connection)?;
            let lease_expires_at = checkpoint
                .lease_expires_at
                .ok_or(MetricIngestionErrorCode::InternalStateInconsistency)?;
            let source_account = eligible
                .iter()
                .find(|account| account.source_account_id == checkpoint.source_account_id)
                .cloned()
                .ok_or(MetricIngestionErrorCode::InternalStateInconsistency)?;
            claims.push(MetricSourceUnitClaim {
                source: source.clone(),
                source_account,
                checkpoint,
                lease_token,
                lease_expires_at,
            });
        }
        Ok(claims)
    })
}

/// Create, or recover, the one managed-DRIVER import for an upstream report of
/// a claimed account.
///
/// Authority is never taken from the caller: the account comes from its exact
/// code and the live claim, and the publisher from the account's pin. A new
/// import is `PROCESSING` and records discovery on the checkpoint. An existing
/// import for the same `(source_account_id, upstream_report_id)` is returned
/// unchanged, in whatever state it is, only when every immutable value and the
/// manifest envelope match; otherwise nothing changes.
pub fn begin_metric_import(
    db: &PgPool,
    actor: &str,
    input: &BeginMetricImportInput,
) -> LifecycleResult<MetricImport> {
    let keys = validate_begin(input)?;
    let manifest = manifest_envelope(&input.manifest_digest, &keys);

    let mut connection = db.get()?;
    connection.transaction(|connection| {
        let source_account_id: Uuid = metric_source_account::table
            .filter(metric_source_account::code.eq(&input.source_account_code))
            .select(metric_source_account::source_account_id)
            .first(connection)
            .optional()?
            .ok_or(MetricLifecycleError::SourceAccountNotFound)?;
        let checkpoint_id = require_live_claim(connection, source_account_id, input.lease_token)?;

        let account: MetricSourceAccount = metric_source_account::table
            .find(source_account_id)
            .for_share()
            .first(connection)?;
        let source: MetricSource = metric_source::table
            .find(account.source_id)
            .for_share()
            .first(connection)?;
        let publisher_id = check_eligibility(connection, &source, &account, true)?;

        let existing: Option<MetricImport> = metric_import::table
            .filter(metric_import::source_account_id.eq(source_account_id))
            .filter(metric_import::upstream_report_id.eq(&input.upstream_report_id))
            .first(connection)
            .optional()?;
        if let Some(existing) = existing {
            let compatible = existing.publisher_id == Some(publisher_id)
                && existing.format_code == input.format_code
                && existing.format_version == input.format_version
                && existing.normalizer_version == input.normalizer_version
                && existing.raw_object_key.is_none()
                && existing.raw_sha256 == input.raw_sha256
                && existing.period_start == Some(input.period_start)
                && existing.period_end == Some(input.period_end)
                && existing.manifest == manifest;
            return if compatible {
                Ok(existing)
            } else {
                Err(MetricLifecycleError::ImportIdempotencyMismatch)
            };
        }

        let import: MetricImport = diesel::insert_into(metric_import::table)
            .values((
                metric_import::source_account_id.eq(source_account_id),
                metric_import::publisher_id.eq(publisher_id),
                metric_import::format_code.eq(&input.format_code),
                metric_import::format_version.eq(&input.format_version),
                metric_import::raw_object_key.eq(None::<String>),
                metric_import::raw_sha256.eq(input.raw_sha256.as_deref()),
                metric_import::upstream_report_id.eq(&input.upstream_report_id),
                metric_import::period_start.eq(input.period_start),
                metric_import::period_end.eq(input.period_end),
                metric_import::status.eq(MetricImportStatus::Processing),
                metric_import::normalizer_version.eq(&input.normalizer_version),
                metric_import::manifest.eq(&manifest),
                metric_import::created_by.eq(actor),
            ))
            .get_result(connection)?;
        sql_query(
            "UPDATE metric_source_checkpoint \
                SET last_discovered_at = transaction_timestamp() \
              WHERE source_checkpoint_id = $1",
        )
        .bind::<SqlUuid, _>(checkpoint_id)
        .execute(connection)?;
        Ok(import)
    })
}

/// Ingest one expected batch of a claimed import through the canonical
/// coordinator, under the two-connection lease guard.
///
/// The guard transaction locks and validates the checkpoint and the batch key,
/// then — still holding that lock — calls the unchanged coordinator on its own
/// pooled connection. The coordinator's result, success or failure, is
/// returned as it is; a coordinator failure is carried by its authoritative
/// code. A replay of a committed batch returns the persisted outcome.
pub fn ingest_metric_batch_under_claim(
    db: &PgPool,
    input: &IngestMetricBatchInput,
) -> LifecycleResult<MetricBatchResult> {
    let batch = to_coordinator_batch(input)?;

    let mut guard = db.get()?;
    guard.transaction(|connection| {
        let import = find_import(connection, input.import_id)?;
        require_live_claim(connection, import.source_account_id, input.lease_token)?;
        let expected = expected_batch_keys(&import.manifest)
            .ok_or(MetricLifecycleError::InvalidImportState)?;
        if !expected.contains(&input.batch_key) {
            return Err(MetricLifecycleError::UnexpectedBatchKey);
        }
        let outcome = ingest_metric_batch(db, &batch)
            .map_err(|error| MetricLifecycleError::Ingestion(error.code))?;
        MetricBatchResult::try_from(outcome)
    })
}

/// Close a claimed import from its committed batches.
///
/// Requires every expected batch key, and no other, to be committed. The
/// terminal status is derived from the coordinator's persisted counters, never
/// from the caller: `COMPLETED` when nothing was invalid or conflicting,
/// otherwise `COMPLETED_WITH_ERRORS`. An already terminal import is returned
/// unchanged.
pub fn complete_metric_import(
    db: &PgPool,
    input: &CompleteMetricImportInput,
) -> LifecycleResult<MetricImport> {
    let mut connection = db.get()?;
    connection.transaction(|connection| {
        let import = find_import(connection, input.import_id)?;
        require_live_claim(connection, import.source_account_id, input.lease_token)?;
        let import: MetricImport = metric_import::table
            .find(input.import_id)
            .for_update()
            .first(connection)?;
        let expected = expected_batch_keys(&import.manifest)
            .ok_or(MetricLifecycleError::InvalidImportState)?;
        match import.status {
            MetricImportStatus::Completed | MetricImportStatus::CompletedWithErrors => {
                return Ok(import)
            }
            MetricImportStatus::Processing => {}
            _ => return Err(MetricLifecycleError::InvalidImportState),
        }

        let committed: BTreeSet<String> = metric_import_batch::table
            .filter(metric_import_batch::import_id.eq(import.import_id))
            .select(metric_import_batch::batch_key)
            .load::<String>(connection)?
            .into_iter()
            .collect();
        if !committed.is_subset(&expected) {
            return Err(MetricLifecycleError::InvalidImportState);
        }
        if committed != expected {
            return Err(MetricLifecycleError::ImportIncomplete);
        }

        let status = if import.invalid_count == 0 && import.conflict_count == 0 {
            MetricImportStatus::Completed
        } else {
            MetricImportStatus::CompletedWithErrors
        };
        Ok(diesel::update(metric_import::table.find(import.import_id))
            .set((
                metric_import::status.eq(status),
                metric_import::completed_at.eq(diesel::dsl::sql::<Nullable<Timestamptz>>(
                    "transaction_timestamp()",
                )),
            ))
            .get_result(connection)?)
    })
}

#[derive(diesel::QueryableByName)]
struct CoverageEvidence {
    #[diesel(sql_type = BigInt)]
    total: i64,
    #[diesel(sql_type = BigInt)]
    complete_for_period: i64,
}

/// Record a terminal import on its account's checkpoint and release the claim.
///
/// `last_completed_at` moves forward to the import's `completed_at` and never
/// back. `last_successful_period_end` moves forward to the import's period end
/// only for a `COMPLETED` import with at least one coverage row, every one of
/// which covers exactly the import's one-day period and is `COMPLETE`; it
/// never moves back. Zero coverage rows are not evidence of success.
///
/// A repeat after the claim was already released returns the checkpoint
/// unchanged when this import's progress is already recorded on it; it never
/// writes. Any other call without the live claim changes nothing.
pub fn update_metric_source_checkpoint(
    db: &PgPool,
    input: &UpdateMetricSourceCheckpointInput,
) -> LifecycleResult<MetricSourceCheckpoint> {
    let mut connection = db.get()?;
    connection.transaction(|connection| {
        let import = find_import(connection, input.import_id)?;
        let locked = lock_checkpoint(connection, import.source_account_id)?
            .ok_or(MetricLifecycleError::StaleSourceClaim)?;
        let import: MetricImport = metric_import::table
            .find(input.import_id)
            .for_share()
            .first(connection)?;
        let live = holds_live_claim(&locked, input.lease_token);
        let released = locked.lease_owner.is_none();
        if !live && !released {
            return Err(MetricLifecycleError::StaleSourceClaim);
        }

        let terminal = matches!(
            import.status,
            MetricImportStatus::Completed | MetricImportStatus::CompletedWithErrors
        );
        let one_day = match (import.period_start, import.period_end) {
            (Some(start), Some(end)) if start.succ_opt() == Some(end) => Some((start, end)),
            _ => None,
        };
        let valid = terminal && expected_batch_keys(&import.manifest).is_some();
        let (Some((period_start, period_end)), Some(completed_at), true) =
            (one_day, import.completed_at, valid)
        else {
            return Err(if live {
                MetricLifecycleError::InvalidImportState
            } else {
                MetricLifecycleError::StaleSourceClaim
            });
        };

        let evidence: CoverageEvidence = sql_query(
            "SELECT COUNT(*) AS total, \
                    COUNT(*) FILTER (WHERE coverage_status = 'COMPLETE' \
                                       AND period_start = $2 \
                                       AND period_end = $3) AS complete_for_period \
               FROM metric_coverage \
              WHERE import_id = $1",
        )
        .bind::<SqlUuid, _>(import.import_id)
        .bind::<SqlDate, _>(period_start)
        .bind::<SqlDate, _>(period_end)
        .get_result(connection)?;
        let successful = import.status == MetricImportStatus::Completed
            && evidence.total >= 1
            && evidence.complete_for_period == evidence.total;

        if !live {
            let checkpoint: MetricSourceCheckpoint = metric_source_checkpoint::table
                .find(locked.source_checkpoint_id)
                .first(connection)?;
            let recorded = checkpoint
                .last_completed_at
                .is_some_and(|recorded| recorded >= completed_at)
                && (!successful
                    || checkpoint
                        .last_successful_period_end
                        .is_some_and(|recorded| recorded >= period_end));
            return if recorded {
                Ok(checkpoint)
            } else {
                Err(MetricLifecycleError::StaleSourceClaim)
            };
        }

        sql_query(
            "UPDATE metric_source_checkpoint \
                SET last_completed_at = GREATEST(COALESCE(last_completed_at, $1), $1), \
                    last_successful_period_end = CASE \
                        WHEN $2 THEN GREATEST(COALESCE(last_successful_period_end, $3), $3) \
                        ELSE last_successful_period_end END, \
                    lease_owner = NULL, \
                    lease_expires_at = NULL \
              WHERE source_checkpoint_id = $4",
        )
        .bind::<Timestamptz, _>(completed_at)
        .bind::<Bool, _>(successful)
        .bind::<SqlDate, _>(period_end)
        .bind::<SqlUuid, _>(locked.source_checkpoint_id)
        .execute(connection)?;
        Ok(metric_source_checkpoint::table
            .find(locked.source_checkpoint_id)
            .first(connection)?)
    })
}
