//! The canonical outbound OPERAS export ledger (`MET-WP1-09`).
//!
//! This module owns the persisted `metric_operas_export` model: the durable
//! record of one outbound OPERAS export for one canonical metric-record
//! revision, using one configured `MET-WP1-08` OPERAS mapping. The approved
//! Metrics design assigns the OPERAS synchronization ledgers to Thoth, and
//! this row is the durable idempotency and audit boundary a later external
//! OPERAS write must be reconciled against.
//!
//! `MET-WP1-09` stores export-ledger state only. It implements **no** outbound
//! eligibility, source-period finalization, `METRICS_OPERAS_EXPORT` capability
//! enforcement, export status vocabulary or transition graph, claim owner,
//! lease, claim token, retry schedule, backoff or stale-claim recovery
//! protocol, attempt-increment behaviour, payload construction, normalization
//! or hashing, OPERAS network client, remote-event recording, correction or
//! divergence handling, inbound synchronization or reconciliation: those
//! belong to the later bounded WP5/WP9 work. Nothing creates or claims an
//! export row at runtime, and the module exposes no GraphQL, authorization or
//! administration surface. The `metric_operas_import`,
//! `metric_reconciliation_run` and `metric_reconciliation_issue` ledgers
//! remain approved future architecture and are deliberately not created by
//! this slice.
//!
//! **Retry-time boundary (reviewed).** The approved design's section 6.14
//! fixes the ten fields below and contains no retry-time column, while its
//! section 14.4 refers to OPERAS export indexes on status and retry time. The
//! independently approved decision is a deliberate deferral to WP9: no
//! `retry_at`, `next_attempt_at` or equivalent field is invented here, and no
//! speculative status/retry index is created, because the claim query and its
//! runtime protocol are not yet defined. WP9 owns the eventual claim/retry
//! representation together with its query and index contract.
//!
//! ADR-0001 remains the entitlement authority: later OPERAS export eligibility
//! must consume the shared `METRICS_OPERAS_EXPORT` capability through
//! `ThothPackage`/`PublisherCapability` rather than any Metrics-specific
//! entitlement state, and nothing here evaluates a capability. ADR-0002
//! likewise remains binding: `MetricPlatform` is not `DistributionPlatform`,
//! and this module introduces no conversion between them. Under ADR-0002 and
//! the approved design, Sphinx stays stateless orchestration and holds no
//! direct canonical database authority; this slice grants it none and creates
//! no contract it could consume.
//!
//! No export row is seeded, and no real OPERAS mapping is approved or guessed.

use uuid::Uuid;

use crate::model::Timestamp;

/// One persisted outbound OPERAS export-ledger row.
///
/// `export_id` is the repository-standard Metrics UUID surrogate identity,
/// generated by the database default when it is not supplied.
///
/// The database enforces `UNIQUE(record_revision_id)`, so at most one durable
/// export row exists per canonical revision. That is the approved idempotency
/// boundary: outbound eligibility is phrased in singular terms — the revision
/// must not already have been exported — and the approved design retries and
/// claims one durable row rather than creating a new row per attempt.
/// Uniqueness alone defines no success/failure transition, no retry
/// eligibility and no reaction to later mapping administration.
///
/// Both foreign keys — to the `MET-WP1-04` canonical revision and to the
/// `MET-WP1-08` OPERAS mapping used for the export — are single-column and
/// non-cascading, so deleting referenced canonical history or interoperability
/// configuration fails rather than erasing durable export evidence.
///
/// The row deliberately does **not** duplicate `record_id`, `platform_id` or
/// `measure_id`, and no trigger asserts that `mapping_id` is the mapping for
/// the revision's own platform/measure pair. That cross-table correspondence
/// stays a required later fail-closed enqueue/eligibility validation, which
/// must select the mapping from the revision's canonical record. This slice
/// exposes no runtime write path, so an arbitrary pair of individually valid
/// identifiers remains representable at raw database level and nothing here
/// may be read as a claim that correspondence is enforced.
///
/// `status` is required `String` with no PostgreSQL enum, no CHECK enumerating
/// values, no default and no trigger: the database only rejects blank and
/// whitespace-only text through the existing Metrics required-text idiom. The
/// approved design fixes no export status vocabulary, so a stored value is
/// evidence of nonblank text and never of a recognised state.
///
/// `attempt_count` is a required `i32` the database constrains to be
/// non-negative, with deliberately **no** default: this slice defines neither
/// when an attempt starts nor when the counter increments, so a later reviewed
/// enqueue path must state the initial value explicitly.
///
/// `remote_event_id`, `request_hash` and `last_error` stay nullable, because
/// the row exists before any delivery attempt. `remote_event_id` and
/// `request_hash` carry only the nullable form of the required-text idiom —
/// nonblank when supplied — with no invented syntax, algorithm, encoding,
/// length or uniqueness rule; two export rows may legitimately produce equal
/// payload content, and revision uniqueness rather than global hash uniqueness
/// owns canonical idempotency. `last_error` carries no format or retention
/// semantics.
///
/// `created_at` uses the repository-standard current-time default.
/// `completed_at` is nullable with no default and deliberately no cross-column
/// invariant tying it to `status` or to any populated delivery result.
#[cfg_attr(feature = "backend", derive(diesel::Queryable))]
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MetricOperasExport {
    pub export_id: Uuid,
    pub record_revision_id: Uuid,
    pub mapping_id: Uuid,
    pub status: String,
    pub attempt_count: i32,
    pub remote_event_id: Option<String>,
    pub request_hash: Option<String>,
    pub last_error: Option<String>,
    pub created_at: Timestamp,
    pub completed_at: Option<Timestamp>,
}

#[cfg(all(test, feature = "backend"))]
pub(crate) mod tests;
